package pty

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type shellPaneLaunch struct {
	command *exec.Cmd
	env     []string
	cleanup func()
}

type shellStartupStrategy func(shellPath string, env []string) (shellPaneLaunch, error)

// shellStartupStrategies lists shells whose startup contracts let attn restore
// PATH after user configuration has run. Add a strategy here when supporting a
// new shell; shells without one retain their normal login launch unchanged.
var shellStartupStrategies = map[string]shellStartupStrategy{
	"zsh":  prepareZshShellPaneLaunch,
	"bash": preparePOSIXShellPaneLaunch,
	"sh":   preparePOSIXShellPaneLaunch,
	"fish": prepareFishShellPaneLaunch,
}

// prepareShellPaneLaunch preserves the user's single interactive login shell
// while restoring the launch PATH after its personal startup files when the
// shell has a supported post-startup hook. A normal cmd.Env assignment is not
// enough for those shells: login and interactive rc files run after exec and
// may prepend an old attn installation. Other shells retain their prior -l
// launch instead of being silently replaced with a different interpreter.
func prepareShellPaneLaunch(shellPath string, env []string) (shellPaneLaunch, error) {
	for _, name := range shellNames(shellPath) {
		if strategy, ok := shellStartupStrategies[name]; ok {
			return strategy(shellPath, env)
		}
	}
	return shellPaneLaunch{
		command: exec.Command(shellPath, "-l"),
		env:     append([]string(nil), env...),
		cleanup: func() {},
	}, nil
}

func shellNames(shellPath string) []string {
	names := []string{strings.TrimSuffix(filepath.Base(shellPath), ".exe")}
	if resolved, err := filepath.EvalSymlinks(shellPath); err == nil {
		resolvedName := strings.TrimSuffix(filepath.Base(resolved), ".exe")
		if resolvedName != names[0] {
			names = append(names, resolvedName)
		}
	}
	return names
}

func prepareFishShellPaneLaunch(shellPath string, env []string) (shellPaneLaunch, error) {
	path, ok := lookupEnv(env, "PATH")
	if !ok {
		return shellPaneLaunch{}, fmt.Errorf("launch environment is missing PATH")
	}
	return shellPaneLaunch{
		// fish runs -C commands after config.fish, so this is the final startup
		// action before it accepts terminal input.
		command: exec.Command(shellPath, "-l", "-C", "set -gx PATH "+shellQuote(path)),
		env:     env,
		cleanup: func() {},
	}, nil
}

func prepareZshShellPaneLaunch(shellPath string, env []string) (shellPaneLaunch, error) {
	overlay, err := os.MkdirTemp("", "attn-zsh-startup-")
	if err != nil {
		return shellPaneLaunch{}, fmt.Errorf("create zsh startup overlay: %w", err)
	}
	cleanup := func() { _ = os.RemoveAll(overlay) }
	path, ok := lookupEnv(env, "PATH")
	if !ok {
		cleanup()
		return shellPaneLaunch{}, errors.New("launch environment is missing PATH")
	}
	userZdotdir, zdotdirSet := lookupEnv(env, "ZDOTDIR")
	if !zdotdirSet {
		userZdotdir, _ = lookupEnv(env, "HOME")
	}
	if userZdotdir == "" {
		cleanup()
		return shellPaneLaunch{}, errors.New("launch environment is missing HOME and ZDOTDIR")
	}

	for _, file := range []string{".zshenv", ".zprofile", ".zshrc", ".zlogin"} {
		final := file == ".zlogin"
		if err := os.WriteFile(filepath.Join(overlay, file), []byte(zshStartupOverlay(file, final)), 0o600); err != nil {
			cleanup()
			return shellPaneLaunch{}, fmt.Errorf("write zsh startup overlay %s: %w", file, err)
		}
	}
	if err := os.WriteFile(filepath.Join(overlay, zshIntegrationFile), []byte(zshOSC133Integration), 0o600); err != nil {
		cleanup()
		return shellPaneLaunch{}, fmt.Errorf("write zsh shell integration: %w", err)
	}

	launchEnv := MergeEnvironment(env, []string{
		"ZDOTDIR=" + overlay,
		"ATTN_SHELL_INIT_DIR=" + overlay,
		"ATTN_SHELL_LAUNCH_PATH=" + path,
		"ATTN_SHELL_USER_ZDOTDIR=" + userZdotdir,
		"ATTN_SHELL_USER_ZDOTDIR_IS_SET=" + boolEnvValue(zdotdirSet),
	})
	return shellPaneLaunch{
		command: exec.Command(shellPath, "-l"),
		env:     launchEnv,
		cleanup: cleanup,
	}, nil
}

// OSC 133 shell integration for shells that do not emit the markers natively
// (fish does; zsh and bash need help). The marks give attn instant
// command-start/end state edges with exit codes (internal/pty/shell_signals.go)
// and command blocks in the terminal UI. Both scripts live as files in the
// startup overlay and are sourced behind a POSIX-safe interpreter guard, so a
// different shell parsing the overlay (including the fake /bin/sh shells the
// tests use) never sees the zsh/bash-only syntax. ATTN_NO_SHELL_INTEGRATION=1
// is the user's opt-out.
const (
	zshIntegrationFile  = "attn-osc133.zsh"
	bashIntegrationFile = "attn-osc133.bash"
)

const zshOSC133Integration = `# Generated by attn. Emit OSC 133 prompt/command marks so attn can read the
# shell's state and group command blocks. Opt out by exporting
# ATTN_NO_SHELL_INTEGRATION=1.
[[ -o interactive ]] || return 0

_attn_osc133_precmd() {
  local attn_status=$?
  if [[ -n ${_attn_osc133_ran-} ]]; then
    unset _attn_osc133_ran
    builtin printf '\033]133;D;%d\007' "$attn_status"
  fi
  builtin printf '\033]133;A\007'
}
_attn_osc133_preexec() {
  typeset -g _attn_osc133_ran=1
  # cmdline_url is percent-encoded just enough to survive the OSC payload:
  # '%' so decoding is unambiguous, ';' (the payload field separator), and the
  # control bytes that would terminate or corrupt the sequence. Everything
  # else, UTF-8 included, passes through raw.
  local cmd=$1
  cmd=${cmd//\%/%25}
  cmd=${cmd//\;/%3B}
  cmd=${cmd//$'\e'/%1B}
  cmd=${cmd//$'\a'/%07}
  cmd=${cmd//$'\n'/%0A}
  cmd=${cmd//$'\r'/%0D}
  builtin printf '\033]133;C;cmdline_url=%s\007' "$cmd"
}

# Prepended, not appended: the exit status a precmd hook sees is whatever the
# previous hook left in $?, so the reporter must run before the user's hooks.
# The filter makes re-sourcing idempotent.
typeset -ga precmd_functions preexec_functions
precmd_functions=(_attn_osc133_precmd ${precmd_functions:#_attn_osc133_precmd})
preexec_functions=(_attn_osc133_preexec ${preexec_functions:#_attn_osc133_preexec})
`

const bashOSC133Integration = `# Generated by attn. Emit OSC 133 prompt/command marks so attn can read the
# shell's state and group command blocks. Opt out by exporting
# ATTN_NO_SHELL_INTEGRATION=1.
[[ $- == *i* ]] || return 0

# Runs first in PROMPT_COMMAND: the exit status a later element sees is
# whatever the previous element left in $?, so the interactive command's
# status must be captured before anything else runs (the bash-preexec
# precedent). Disarming here keeps a DEBUG fire for the user's own
# PROMPT_COMMAND entries from reading as a command start on a bare Enter.
_attn_osc133_status() { _attn_osc133_last_status=$?; unset _attn_osc133_armed; }

# Called once, from the first prompt, with the top-level DEBUG trap listing as
# its argument. The DEBUG trap is the only pre-exec hook every bash has (PS0
# needs 4.4, and macOS ships 3.2), so a free trap is claimed here — installing
# from a function body persists on every bash when no trap existed, and a trap
# the user owns is never touched (bash 3.2 silently restores a startup-time
# trap over one set inside a sourced file, while 5.x lets the sourced file
# clobber it, so installation cannot happen at source time at all). A user-
# owned trap — or extdebug, where a DEBUG handler's return value can make bash
# skip the user's command — selects the fallback: PS0 (where it exists) still
# gives a bare C mark, and D degrades to every prompt after the first since
# nothing tracks whether a command ran.
_attn_osc133_init() {
  if [[ -z $1 ]] && ! shopt -q extdebug; then
    trap '_attn_osc133_preexec' DEBUG
    _attn_osc133_mode=trap
  else
    _attn_osc133_mode=fallback
    PS0="${PS0-}"'\e]133;C\a'
  fi
}

_attn_osc133_precmd() {
  if [[ -n ${_attn_osc133_ran-} ]] || [[ ${_attn_osc133_mode-} == fallback && -n ${_attn_osc133_primed-} ]]; then
    unset _attn_osc133_ran
    printf '\033]133;D;%d\007' "${_attn_osc133_last_status:-0}"
  fi
  _attn_osc133_primed=1
  printf '\033]133;A\007'
  _attn_osc133_armed=1
}

# The pre-exec mark. Armed at the end of each prompt cycle, so the first DEBUG
# fire that is a real command — not completion, not our own hooks — is the one
# that marks the start; a compound line marks once, carrying its first simple
# command. The saved $? is returned so the trap is transparent to
# _attn_osc133_status (bash discards the trap's own status, but not if we
# return early through the guards).
_attn_osc133_preexec() {
  local attn_ret=$?
  if [[ -z ${COMP_LINE-} && -n ${_attn_osc133_armed-} ]]; then
    case "$BASH_COMMAND" in
    _attn_osc133_*) ;;
    *)
      unset _attn_osc133_armed
      _attn_osc133_ran=1
      local cmd=$BASH_COMMAND
      cmd=${cmd//\%/%25}
      cmd=${cmd//\;/%3B}
      cmd=${cmd//$'\e'/%1B}
      cmd=${cmd//$'\a'/%07}
      cmd=${cmd//$'\n'/%0A}
      cmd=${cmd//$'\r'/%0D}
      printf '\033]133;C;cmdline_url=%s\007' "$cmd"
      ;;
    esac
  fi
  return "$attn_ret"
}

# The mode probe must stay inline in PROMPT_COMMAND — inside this sourced
# file (or any function body) $(trap -p DEBUG) reads empty whether or not the
# user has a trap, but arguments to a call written at top level are expanded
# at top level, where the listing is truthful. Status capture still comes
# first: the probe would overwrite the interactive command's $?.
_attn_osc133_probe='_attn_osc133_status; [[ -n ${_attn_osc133_mode-} ]] || _attn_osc133_init "$(trap -p DEBUG)"'
if [[ $(declare -p PROMPT_COMMAND 2>/dev/null) == 'declare -a'* ]]; then
  PROMPT_COMMAND=("$_attn_osc133_probe" "${PROMPT_COMMAND[@]}" _attn_osc133_precmd)
else
  PROMPT_COMMAND="$_attn_osc133_probe${PROMPT_COMMAND:+;$PROMPT_COMMAND};_attn_osc133_precmd"
fi
unset _attn_osc133_probe
`

func zshStartupOverlay(file string, final bool) string {
	content := `# Generated by attn. Source the user's corresponding startup file,
# then restore the launch PATH after that startup phase has finished.
if [ "${ATTN_SHELL_USER_ZDOTDIR_IS_SET:-0}" = "1" ]; then
  ZDOTDIR="$ATTN_SHELL_USER_ZDOTDIR"
  export ZDOTDIR
else
  unset ZDOTDIR
fi
attn_startup_file="${ZDOTDIR:-$HOME}/` + file + `"
if [ -r "$attn_startup_file" ]; then
  . "$attn_startup_file"
fi
if [ -n "${ZDOTDIR+x}" ]; then
  ATTN_SHELL_USER_ZDOTDIR="$ZDOTDIR"
  ATTN_SHELL_USER_ZDOTDIR_IS_SET=1
else
  ATTN_SHELL_USER_ZDOTDIR="${HOME:?HOME is required when ZDOTDIR is unset}"
  ATTN_SHELL_USER_ZDOTDIR_IS_SET=0
fi
export ATTN_SHELL_USER_ZDOTDIR ATTN_SHELL_USER_ZDOTDIR_IS_SET
PATH="$ATTN_SHELL_LAUNCH_PATH"
export PATH
unset attn_startup_file
`
	if file == ".zshrc" {
		// After the user's rc so their config cannot clobber the hooks. The
		// guard stays POSIX: only real zsh ever parses the integration file.
		content += `if [ -n "${ZSH_VERSION-}" ] && [ -z "${ATTN_NO_SHELL_INTEGRATION-}" ] && [ -r "$ATTN_SHELL_INIT_DIR/` + zshIntegrationFile + `" ]; then
  . "$ATTN_SHELL_INIT_DIR/` + zshIntegrationFile + `"
fi
`
	}
	if !final {
		return content + `ZDOTDIR="$ATTN_SHELL_INIT_DIR"
export ZDOTDIR
`
	}
	return content + `if [ "$ATTN_SHELL_USER_ZDOTDIR_IS_SET" = "1" ]; then
  ZDOTDIR="$ATTN_SHELL_USER_ZDOTDIR"
  export ZDOTDIR
else
  unset ZDOTDIR
fi
unset ATTN_SHELL_INIT_DIR ATTN_SHELL_LAUNCH_PATH ATTN_SHELL_USER_ZDOTDIR ATTN_SHELL_USER_ZDOTDIR_IS_SET
`
}

func preparePOSIXShellPaneLaunch(shellPath string, env []string) (shellPaneLaunch, error) {
	overlay, err := os.MkdirTemp("", "attn-shell-startup-")
	if err != nil {
		return shellPaneLaunch{}, fmt.Errorf("create shell startup overlay: %w", err)
	}
	cleanup := func() { _ = os.RemoveAll(overlay) }
	path, ok := lookupEnv(env, "PATH")
	if !ok {
		cleanup()
		return shellPaneLaunch{}, errors.New("launch environment is missing PATH")
	}
	userHome, ok := lookupEnv(env, "HOME")
	if !ok || userHome == "" {
		cleanup()
		return shellPaneLaunch{}, errors.New("launch environment is missing HOME")
	}

	isBash := filepath.Base(shellPath) == "bash"
	profile := posixStartupOverlay(isBash)
	if err := os.WriteFile(filepath.Join(overlay, ".bash_profile"), []byte(profile), 0o600); err != nil {
		cleanup()
		return shellPaneLaunch{}, fmt.Errorf("write bash startup overlay: %w", err)
	}
	if err := os.WriteFile(filepath.Join(overlay, ".profile"), []byte(profile), 0o600); err != nil {
		cleanup()
		return shellPaneLaunch{}, fmt.Errorf("write sh startup overlay: %w", err)
	}
	if isBash {
		if err := os.WriteFile(filepath.Join(overlay, bashIntegrationFile), []byte(bashOSC133Integration), 0o600); err != nil {
			cleanup()
			return shellPaneLaunch{}, fmt.Errorf("write bash shell integration: %w", err)
		}
	}

	launchEnv := MergeEnvironment(env, []string{
		"HOME=" + overlay,
		"ATTN_SHELL_USER_HOME=" + userHome,
		"ATTN_SHELL_LAUNCH_PATH=" + path,
		"ATTN_SHELL_INIT_DIR=" + overlay,
	})
	return shellPaneLaunch{
		command: exec.Command(shellPath, "-l"),
		env:     launchEnv,
		cleanup: cleanup,
	}, nil
}

func posixStartupOverlay(bash bool) string {
	// bash (and shells built on its POSIX-mode startup, such as macOS's
	// /bin/sh) cache the "~" home directory the first time it is looked up
	// during shell startup and do not re-derive it after this script
	// reassigns and exports HOME, even though $HOME itself reads back
	// correctly. Left alone, the very first "~" reference in the user's own
	// startup files - commonly a plain `source ~/.bashrc` - resolves
	// against this overlay's ephemeral directory instead of the real home,
	// producing a spurious "No such file or directory" before the user's
	// startup can run. Forking one throwaway external command flushes that
	// stale cache as a side effect, so run it before sourcing anything that
	// might use "~".
	const warmup = `if [ -x /usr/bin/true ]; then
  /usr/bin/true
fi
`
	if bash {
		return `# Generated by attn. Preserve the user's login startup order, then
# restore the launch PATH after that startup has completed.
HOME="$ATTN_SHELL_USER_HOME"
export HOME
` + warmup + `if [ -r "$HOME/.bash_profile" ]; then
  . "$HOME/.bash_profile"
elif [ -r "$HOME/.bash_login" ]; then
  . "$HOME/.bash_login"
elif [ -r "$HOME/.profile" ]; then
  . "$HOME/.profile"
fi
PATH="$ATTN_SHELL_LAUNCH_PATH"
export PATH
if [ -n "${BASH_VERSION-}" ] && [ -z "${ATTN_NO_SHELL_INTEGRATION-}" ] && [ -r "$ATTN_SHELL_INIT_DIR/` + bashIntegrationFile + `" ]; then
  . "$ATTN_SHELL_INIT_DIR/` + bashIntegrationFile + `"
fi
unset ATTN_SHELL_USER_HOME ATTN_SHELL_LAUNCH_PATH ATTN_SHELL_INIT_DIR
`
	}
	return `# Generated by attn. Preserve the user's login startup order, then
# restore the launch PATH after that startup has completed.
HOME="$ATTN_SHELL_USER_HOME"
export HOME
` + warmup + `if [ -r "$HOME/.profile" ]; then
  . "$HOME/.profile"
fi
PATH="$ATTN_SHELL_LAUNCH_PATH"
export PATH
unset ATTN_SHELL_USER_HOME ATTN_SHELL_LAUNCH_PATH ATTN_SHELL_INIT_DIR
`
}

func lookupEnv(env []string, key string) (string, bool) {
	prefix := key + "="
	for _, entry := range env {
		if strings.HasPrefix(entry, prefix) {
			return strings.TrimPrefix(entry, prefix), true
		}
	}
	return "", false
}

func boolEnvValue(value bool) string {
	if value {
		return "1"
	}
	return "0"
}
