package pty

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type shellPaneLaunch struct {
	command *exec.Cmd
	env     []string
	cleanup func()
}

type shellStartupStrategy func(shellPath string, env []string) (shellPaneLaunch, error)

// shellStartupStrategies lists shells whose startup contracts let attn restore
// PATH after user configuration has run. Add a strategy here when supporting a
// new shell; shells without one retain their normal login launch unchanged.
var shellStartupStrategies = map[string]shellStartupStrategy{
	"zsh":  prepareZshShellPaneLaunch,
	"bash": preparePOSIXShellPaneLaunch,
	"sh":   preparePOSIXShellPaneLaunch,
	"fish": prepareFishShellPaneLaunch,
}

// prepareShellPaneLaunch preserves the user's single interactive login shell
// while restoring the launch PATH after its personal startup files when the
// shell has a supported post-startup hook. A normal cmd.Env assignment is not
// enough for those shells: login and interactive rc files run after exec and
// may prepend an old attn installation. Other shells retain their prior -l
// launch instead of being silently replaced with a different interpreter.
func prepareShellPaneLaunch(shellPath string, env []string) (shellPaneLaunch, error) {
	for _, name := range shellNames(shellPath) {
		if strategy, ok := shellStartupStrategies[name]; ok {
			return strategy(shellPath, env)
		}
	}
	return shellPaneLaunch{
		command: exec.Command(shellPath, "-l"),
		env:     append([]string(nil), env...),
		cleanup: func() {},
	}, nil
}

func shellNames(shellPath string) []string {
	names := []string{strings.TrimSuffix(filepath.Base(shellPath), ".exe")}
	if resolved, err := filepath.EvalSymlinks(shellPath); err == nil {
		resolvedName := strings.TrimSuffix(filepath.Base(resolved), ".exe")
		if resolvedName != names[0] {
			names = append(names, resolvedName)
		}
	}
	return names
}

func prepareFishShellPaneLaunch(shellPath string, env []string) (shellPaneLaunch, error) {
	path, ok := lookupEnv(env, "PATH")
	if !ok {
		return shellPaneLaunch{}, fmt.Errorf("launch environment is missing PATH")
	}
	return shellPaneLaunch{
		// fish runs -C commands after config.fish, so this is the final startup
		// action before it accepts terminal input.
		command: exec.Command(shellPath, "-l", "-C", "set -gx PATH "+shellQuote(path)),
		env:     env,
		cleanup: func() {},
	}, nil
}

func prepareZshShellPaneLaunch(shellPath string, env []string) (shellPaneLaunch, error) {
	overlay, err := os.MkdirTemp("", "attn-zsh-startup-")
	if err != nil {
		return shellPaneLaunch{}, fmt.Errorf("create zsh startup overlay: %w", err)
	}
	cleanup := func() { _ = os.RemoveAll(overlay) }
	path, ok := lookupEnv(env, "PATH")
	if !ok {
		cleanup()
		return shellPaneLaunch{}, errors.New("launch environment is missing PATH")
	}
	userZdotdir, zdotdirSet := lookupEnv(env, "ZDOTDIR")
	if !zdotdirSet {
		userZdotdir, _ = lookupEnv(env, "HOME")
	}
	if userZdotdir == "" {
		cleanup()
		return shellPaneLaunch{}, errors.New("launch environment is missing HOME and ZDOTDIR")
	}

	for _, file := range []string{".zshenv", ".zprofile", ".zshrc", ".zlogin"} {
		final := file == ".zlogin"
		if err := os.WriteFile(filepath.Join(overlay, file), []byte(zshStartupOverlay(file, final)), 0o600); err != nil {
			cleanup()
			return shellPaneLaunch{}, fmt.Errorf("write zsh startup overlay %s: %w", file, err)
		}
	}

	launchEnv := mergeEnvironment(env, []string{
		"ZDOTDIR=" + overlay,
		"ATTN_SHELL_INIT_DIR=" + overlay,
		"ATTN_SHELL_LAUNCH_PATH=" + path,
		"ATTN_SHELL_USER_ZDOTDIR=" + userZdotdir,
		"ATTN_SHELL_USER_ZDOTDIR_IS_SET=" + boolEnvValue(zdotdirSet),
	})
	return shellPaneLaunch{
		command: exec.Command(shellPath, "-l"),
		env:     launchEnv,
		cleanup: cleanup,
	}, nil
}

func zshStartupOverlay(file string, final bool) string {
	content := `# Generated by attn. Source the user's corresponding startup file,
# then restore the launch PATH after that startup phase has finished.
if [ "${ATTN_SHELL_USER_ZDOTDIR_IS_SET:-0}" = "1" ]; then
  ZDOTDIR="$ATTN_SHELL_USER_ZDOTDIR"
  export ZDOTDIR
else
  unset ZDOTDIR
fi
attn_startup_file="${ZDOTDIR:-$HOME}/` + file + `"
if [ -r "$attn_startup_file" ]; then
  . "$attn_startup_file"
fi
if [ -n "${ZDOTDIR+x}" ]; then
  ATTN_SHELL_USER_ZDOTDIR="$ZDOTDIR"
  ATTN_SHELL_USER_ZDOTDIR_IS_SET=1
else
  ATTN_SHELL_USER_ZDOTDIR="${HOME:?HOME is required when ZDOTDIR is unset}"
  ATTN_SHELL_USER_ZDOTDIR_IS_SET=0
fi
export ATTN_SHELL_USER_ZDOTDIR ATTN_SHELL_USER_ZDOTDIR_IS_SET
PATH="$ATTN_SHELL_LAUNCH_PATH"
export PATH
unset attn_startup_file
`
	if !final {
		return content + `ZDOTDIR="$ATTN_SHELL_INIT_DIR"
export ZDOTDIR
`
	}
	return content + `if [ "$ATTN_SHELL_USER_ZDOTDIR_IS_SET" = "1" ]; then
  ZDOTDIR="$ATTN_SHELL_USER_ZDOTDIR"
  export ZDOTDIR
else
  unset ZDOTDIR
fi
unset ATTN_SHELL_INIT_DIR ATTN_SHELL_LAUNCH_PATH ATTN_SHELL_USER_ZDOTDIR ATTN_SHELL_USER_ZDOTDIR_IS_SET
`
}

func preparePOSIXShellPaneLaunch(shellPath string, env []string) (shellPaneLaunch, error) {
	overlay, err := os.MkdirTemp("", "attn-shell-startup-")
	if err != nil {
		return shellPaneLaunch{}, fmt.Errorf("create shell startup overlay: %w", err)
	}
	cleanup := func() { _ = os.RemoveAll(overlay) }
	path, ok := lookupEnv(env, "PATH")
	if !ok {
		cleanup()
		return shellPaneLaunch{}, errors.New("launch environment is missing PATH")
	}
	userHome, ok := lookupEnv(env, "HOME")
	if !ok || userHome == "" {
		cleanup()
		return shellPaneLaunch{}, errors.New("launch environment is missing HOME")
	}

	profile := posixStartupOverlay(filepath.Base(shellPath) == "bash")
	if err := os.WriteFile(filepath.Join(overlay, ".bash_profile"), []byte(profile), 0o600); err != nil {
		cleanup()
		return shellPaneLaunch{}, fmt.Errorf("write bash startup overlay: %w", err)
	}
	if err := os.WriteFile(filepath.Join(overlay, ".profile"), []byte(profile), 0o600); err != nil {
		cleanup()
		return shellPaneLaunch{}, fmt.Errorf("write sh startup overlay: %w", err)
	}

	launchEnv := mergeEnvironment(env, []string{
		"HOME=" + overlay,
		"ATTN_SHELL_USER_HOME=" + userHome,
		"ATTN_SHELL_LAUNCH_PATH=" + path,
	})
	return shellPaneLaunch{
		command: exec.Command(shellPath, "-l"),
		env:     launchEnv,
		cleanup: cleanup,
	}, nil
}

func posixStartupOverlay(bash bool) string {
	if bash {
		return `# Generated by attn. Preserve the user's login startup order, then
# restore the launch PATH after that startup has completed.
HOME="$ATTN_SHELL_USER_HOME"
export HOME
if [ -r "$HOME/.bash_profile" ]; then
  . "$HOME/.bash_profile"
elif [ -r "$HOME/.bash_login" ]; then
  . "$HOME/.bash_login"
elif [ -r "$HOME/.profile" ]; then
  . "$HOME/.profile"
fi
PATH="$ATTN_SHELL_LAUNCH_PATH"
export PATH
unset ATTN_SHELL_USER_HOME ATTN_SHELL_LAUNCH_PATH
`
	}
	return `# Generated by attn. Preserve the user's login startup order, then
# restore the launch PATH after that startup has completed.
HOME="$ATTN_SHELL_USER_HOME"
export HOME
if [ -r "$HOME/.profile" ]; then
  . "$HOME/.profile"
fi
PATH="$ATTN_SHELL_LAUNCH_PATH"
export PATH
unset ATTN_SHELL_USER_HOME ATTN_SHELL_LAUNCH_PATH
`
}

func lookupEnv(env []string, key string) (string, bool) {
	prefix := key + "="
	for _, entry := range env {
		if strings.HasPrefix(entry, prefix) {
			return strings.TrimPrefix(entry, prefix), true
		}
	}
	return "", false
}

func boolEnvValue(value bool) string {
	if value {
		return "1"
	}
	return "0"
}
