package appbuild

import (
	"fmt"
	"strings"

	"github.com/victorarias/attn/internal/apps"
)

// Codegen is the arrow that keeps the manifest and the code in sync without
// apply ever reading the code: the manifest generates a type, and the compiler
// checks the entrypoint against it.
//
// One file is written into the app, regenerated on every apply and not meant to
// be edited: GeneratedFile, the `Handlers` type derived from `[[subscribe]]` and
// the collection map derived from `[[collections]]`. A declared subscription
// with no handler and a handler with the wrong shape are both tsc errors with a
// filename and a line, from the pass apply already runs.
//
// The SDK itself is no longer generated. It is one TypeScript source in this
// repo, materialized into the app as a package — see sdk.go.
const (
	GeneratedFile = "src/generated.ts"

	// SDKModule is the import specifier apps use. It is a package name a
	// published SDK could still take over later without touching app code.
	SDKModule = "@victorarias/attn-app"

	generatedHeader = "// Generated by attn from " + ManifestName + ". Do not edit — `attn app apply` rewrites it.\n"
)

// SDKSpecifiers is every specifier a view may import from the SDK. Three
// surfaces have to agree on this list and none can see the others: the view
// build marks each one external, the materialized package's exports map
// declares each one, and the frontend's import map resolves each one to a chunk
// of its own build. A specifier missing from any of them is a view that links
// against nothing at mount.
func SDKSpecifiers() []string {
	return []string{SDKModule, SDKModule + "/jsx-runtime", SDKModule + "/jsx-dev-runtime"}
}

// GenerateTypes renders src/generated.ts for a manifest.
func GenerateTypes(m Manifest) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("//\n")
	b.WriteString(fmt.Sprintf("// app %s — bus consumer %s, documents under %s\n",
		m.Name, apps.ConsumerName(m.Name), apps.Namespace(m.Name)))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("import type { AppContext, AppEvent, Collection, ReconcileHandler } from %q\n\n", SDKModule))

	b.WriteString("// The collections this app declared. Reachable as ctx.collections.<name>;\n")
	b.WriteString("// a name that is not declared is a compile error, not an empty read.\n")
	b.WriteString("export type AppCollections = {\n")
	for _, c := range m.Collections {
		b.WriteString(fmt.Sprintf("  %s: Collection\n", tsKey(c.Name)))
	}
	b.WriteString("}\n\n")

	b.WriteString("// The context every handler of this app receives.\n")
	b.WriteString("export type Ctx = AppContext<AppCollections>\n\n")

	b.WriteString("// One group per kind, one entry per declaration. The entrypoint's default\n")
	b.WriteString("// export must `satisfies Handlers`, so a declaration with no handler, a\n")
	b.WriteString("// handler with the wrong shape, and a handler nothing declared are all\n")
	b.WriteString("// compile errors here rather than silence at runtime.\n")
	b.WriteString("//\n")
	b.WriteString("// A subscription is keyed by its event pattern and a command by its bare\n")
	b.WriteString("// name. They cannot collide because they are not in the same map: which kind\n")
	b.WriteString("// is being run is what attn already knows when it dispatches.\n")
	b.WriteString("export type Handlers = {\n")
	writeHandlerGroup(&b, "subscriptions", m.EventPatterns(),
		"(event: AppEvent, ctx: Ctx) => void | Promise<void>")
	writeHandlerGroup(&b, "commands", m.CommandNames(),
		"(payload: unknown, ctx: Ctx) => unknown")
	if m.Reconcile {
		b.WriteString("  reconcile: ReconcileHandler<AppCollections>\n")
	} else {
		b.WriteString("  reconcile?: never\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// writeHandlerGroup renders one kind's group. A kind an app declared nothing of
// is optional and empty, so the entrypoint omits it — and adding a key to it
// stays an error rather than becoming a handler nothing will ever call.
func writeHandlerGroup(b *strings.Builder, group string, keys []string, signature string) {
	if len(keys) == 0 {
		b.WriteString(fmt.Sprintf("  %s?: Record<string, never>\n", group))
		return
	}
	b.WriteString(fmt.Sprintf("  %s: {\n", group))
	for _, key := range keys {
		b.WriteString(fmt.Sprintf("    %s: %s\n", tsKey(key), signature))
	}
	b.WriteString("  }\n")
}

// tsKey renders a manifest string as a TypeScript property key. Event patterns
// carry dots and asterisks and collection names carry dashes, so every key is
// quoted rather than only the ones that need it — one rule, no judgment call at
// the point of writing.
func tsKey(s string) string { return fmt.Sprintf("%q", s) }
