package appbuild

import (
	"fmt"
	"strings"

	"github.com/victorarias/attn/internal/apps"
	"github.com/victorarias/attn/internal/docstore"
)

// Codegen is the arrow that keeps the manifest and the code in sync without
// apply ever reading the code: the manifest generates a type, and the compiler
// checks the entrypoint against it.
//
// Two files are written into the app, both regenerated on every apply and
// neither meant to be edited:
//
//   - GeneratedFile — the `Handlers` type derived from `[[subscribe]]`, and the
//     collection map derived from `[[collections]]`. A declared subscription
//     with no handler and a handler with the wrong shape are both tsc errors
//     with a filename and a line, from the pass apply already runs.
//   - SDKFile — the app SDK's types, as an ambient module declaration. It is
//     written into the app rather than installed because an app needs no
//     node_modules to be typechecked, and because the import specifier in
//     generated code is the one the published package will use: when the SDK
//     ships to npm, this file is deleted and nothing else changes.
const (
	GeneratedFile = "src/generated.ts"
	SDKFile       = "src/attn-app.d.ts"

	// SDKModule is the import specifier apps use. It is the eventual npm package
	// name on purpose — see SDKFile above.
	SDKModule = "@victorarias/attn-app"

	generatedHeader = "// Generated by attn from " + ManifestName + ". Do not edit — `attn app apply` rewrites it.\n"
)

// GenerateTypes renders src/generated.ts for a manifest.
func GenerateTypes(m Manifest) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("//\n")
	b.WriteString(fmt.Sprintf("// app %s — bus consumer %s, documents under %s\n",
		m.Name, apps.ConsumerName(m.Name), apps.Namespace(m.Name)))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("import type { AppContext, AppEvent, Collection } from %q\n\n", SDKModule))

	b.WriteString("// The collections this app declared. Reachable as ctx.collections.<name>;\n")
	b.WriteString("// a name that is not declared is a compile error, not an empty read.\n")
	b.WriteString("export type AppCollections = {\n")
	for _, c := range m.Collections {
		b.WriteString(fmt.Sprintf("  %s: Collection\n", tsKey(c.Name)))
	}
	b.WriteString("}\n\n")

	b.WriteString("// The context every handler of this app receives.\n")
	b.WriteString("export type Ctx = AppContext<AppCollections>\n\n")

	b.WriteString("// One entry per declared subscription. The entrypoint's default export must\n")
	b.WriteString("// `satisfies Handlers`, so a subscription with no handler and a handler with\n")
	b.WriteString("// the wrong shape are both compile errors here rather than silence at runtime.\n")
	b.WriteString("export type Handlers = {\n")
	for _, pattern := range m.EventPatterns() {
		b.WriteString(fmt.Sprintf("  %s: (event: AppEvent, ctx: Ctx) => void | Promise<void>\n", tsKey(pattern)))
	}
	b.WriteString("}\n")
	return b.String()
}

// tsKey renders a manifest string as a TypeScript property key. Event patterns
// carry dots and asterisks and collection names carry dashes, so every key is
// quoted rather than only the ones that need it — one rule, no judgment call at
// the point of writing.
func tsKey(s string) string { return fmt.Sprintf("%q", s) }

// GenerateSDK renders src/attn-app.d.ts: the handler contract, types only.
//
// It describes what slice 5's runtime will provide and nothing more. Everything
// absent is absent on purpose — live queries are the UI host's story (A5), and a
// type for an operation the runtime does not implement is a promise the platform
// has not made.
func GenerateSDK() string {
	return generatedHeader + `//
// The attn app SDK, as types. An app is a set of handlers: attn wakes one when a
// fact it subscribed to lands, hands it the fact and a context scoped to the
// app, and records what happened.

declare module "` + SDKModule + `" {
  /** The app contract version this file describes — attn-app.toml's attn_app_api. */
  export const APP_API_VERSION: ` + fmt.Sprint(APIVersion) + `

  /**
   * One fact from attn's durable event bus.
   *
   * A fact says something happened to something; it is an invalidation, not a
   * payload. A handler that needs the current state reads it — the fact may
   * already be behind by the time the handler runs, and the store is what is
   * true now.
   */
  export interface AppEvent {
    /** Dotted fact name, for example "session.state.changed". */
    readonly name: string
    /** The entity the fact is about — a session id, a ticket id, an app name. */
    readonly subject: string
    /** Position in the durable log. Opaque and monotonic; do not persist it as a cursor. */
    readonly seq: number
    /**
     * The producer's payload, when it carries one. Typed as unknown by design:
     * the SDK gains a type per fact class as each one's shape is documented,
     * and claiming a shape it has not pinned would be worse than honest unknown.
     */
    readonly payload: unknown
    /** When the fact was published, RFC3339. */
    readonly published_at: string
  }

  /** One stored document. Body is what was written, byte for byte. */
  export interface Document<Body = unknown> {
    readonly id: string
    readonly body: Body
    /**
     * Counts writes to this document. Hand it back to put() to refuse an edit
     * built on a version somebody else has already replaced.
     */
    readonly rev: number
    readonly created_at: string
    readonly updated_at: string
  }

  /** The comparisons a declared field supports. */
  export type FilterOp = "` + strings.Join(filterOps(), `" | "`) + `"

  export interface Filter {
    /** A field this collection declared, or ` + "`created_at`" + ` / ` + "`updated_at`" + `. */
    field: string
    op: FilterOp
    value: string | number | boolean
  }

  export interface QueryOptions {
    filters?: Filter[]
    sort?: { field: string; desc?: boolean }
    /** Defaults to ` + fmt.Sprint(docstore.DefaultLimit) + `, and refuses more than ` + fmt.Sprint(docstore.MaxLimit) + `. */
    limit?: number
    /** The id of the previous page's last document. */
    after?: string
  }

  export interface PutOptions {
    /**
     * The rev the caller read. The write is refused when the stored document
     * has moved on, which is how a read-modify-write stays safe without a lock.
     */
    ifRev?: number
  }

  /**
   * One of the app's document collections, scoped to its own namespace. An app
   * can only ever address its own documents: the namespace is derived from the
   * app's name, not passed in.
   */
  export interface Collection {
    get<Body = unknown>(id: string): Promise<Document<Body> | null>
    put<Body = unknown>(id: string, body: Body, options?: PutOptions): Promise<Document<Body>>
    delete(id: string): Promise<boolean>
    query<Body = unknown>(options?: QueryOptions): Promise<Document<Body>[]>
    count(options?: Pick<QueryOptions, "filters">): Promise<number>
  }

  /** What a handler is given besides the fact. */
  export interface AppContext<Collections> {
    /** This app's name — its registry key, its consumer, its namespace. */
    readonly app: string
    /** The version id that is running, which a rollback does not rewrite. */
    readonly version: number
    /** The collections declared in attn-app.toml, by name. */
    readonly collections: Collections
  }

  /**
   * A handler. Throwing fails that delivery: the bus retries it with backoff
   * rather than skipping it, every attempt is recorded, and an app stuck on one
   * event long enough is disabled so a single broken app cannot hold the event
   * log open for everyone.
   */
  export type Handler<Collections> = (
    event: AppEvent,
    ctx: AppContext<Collections>,
  ) => void | Promise<void>
}
`
}

// filterOps mirrors the document store's operator set into the SDK types, from
// the store's own constants — a hand-copied list here would be a second source
// of truth that silently rots the first time the store gains an operator.
func filterOps() []string {
	ops := docstore.FilterOps()
	out := make([]string, 0, len(ops))
	for _, op := range ops {
		out = append(out, string(op))
	}
	return out
}
