#!/bin/bash
# Shared helpers for the BROWSER ghostty-vt.wasm module used by the frontend
# terminal model (app/src/ghostty).
#
# Sourced by app/scripts/ensure-ghostty-vt-wasm.sh (consumer path) and
# scripts/publish-ghostty-vt-wasm.sh (maintainer mirror path). Companion of
# scripts/lib/libghostty-vt.sh, which does the same job for the native archives;
# both read the shared ghostty-vt.pin so the worker and the browser parse VT
# with one implementation.
#
# This file only defines functions and read-only vars; it performs no work and
# is safe to source. Callers must set -euo pipefail themselves.
#
# UPSTREAM-FIRST: ghostty-org builds this binary and publishes it on its rolling
# "tip" release. We do not build it — we mirror the exact upstream bytes for the
# pinned commit onto our own keyed release, because tip is rebuilt on every
# commit to main and its assets cannot be pinned by hash.

# This file lives at <repo>/scripts/lib/ghostty-vt-wasm.sh; repo root is two up.
vtw_lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
vtw_repo_dir="$(cd "$vtw_lib_dir/../.." && pwd)"
vtw_pin_file="$vtw_repo_dir/ghostty-vt.pin"
vtw_lock_file="$vtw_repo_dir/ghostty-vt-wasm.lock"
vtw_output="$vtw_repo_dir/app/vendor/ghostty-vt/ghostty-vt.wasm"

# Our mirror. Shares the rolling release the native prebuilts use; the asset
# name keeps them apart.
VTW_RELEASE_TAG="native-vt-prebuilts"
VTW_REPO="victorarias/attn"

# Upstream's rolling nightly, where the binary is born.
VTW_UPSTREAM_REPO="ghostty-org/ghostty"
VTW_UPSTREAM_TAG="tip"
# ReleaseFast, not the -small variant: the module loads from the app bundle, so
# the 1.1MB/780KB difference buys nothing and the speed is the entire point.
VTW_UPSTREAM_ASSET="ghostty-vt.wasm"

# The ghostty commit from the shared pin file.
vtw_commit() {
  local commit
  commit="$(grep -vE '^\s*(#|$)' "$vtw_pin_file" | head -n1 | tr -d '[:space:]')"
  if [[ -z "$commit" ]]; then
    echo "error: no commit found in $vtw_pin_file" >&2
    return 1
  fi
  printf '%s' "$commit"
}

# Mirrored asset name. Keyed by the pin commit alone — unlike the native side
# there is no carried patch, because we no longer build this artifact.
vtw_asset_name() { printf 'ghostty-vt-%s.wasm' "$(vtw_commit)"; }

vtw_lock_field() {
  local field="$1"
  [[ -f "$vtw_lock_file" ]] || return 0
  grep -E "^${field}=" "$vtw_lock_file" | head -n1 | cut -d= -f2- | tr -d '[:space:]'
}

vtw_sha256() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  elif command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    echo "error: no SHA-256 implementation found (tried shasum, sha256sum)" >&2
    return 1
  fi
}

vtw_write_lock() {
  local tmp
  tmp="$(mktemp "${vtw_lock_file}.XXXXXX")"
  # shellcheck disable=SC2064
  trap "rm -f '$tmp'" RETURN
  {
    echo "# Browser ghostty-vt.wasm provenance. REGENERATED by"
    echo "# make publish-ghostty-vt-wasm; do not hand-edit. The binary is built and"
    echo "# published by ghostty-org; we mirror the exact upstream bytes for the"
    echo "# pinned commit as ghostty-vt-<pin>.wasm on the \"$VTW_RELEASE_TAG\" release,"
    echo "# because upstream's \"tip\" is rebuilt on every commit to main and its"
    echo "# assets cannot be pinned by hash. Consumers download and verify against"
    echo "# sha256 before the module ever reaches a build."
    echo "pin=$(vtw_commit)"
    echo "upstream_asset=$VTW_UPSTREAM_ASSET"
    echo "sha256=$(vtw_sha256 "$vtw_output")"
  } >"$tmp"
  mv "$tmp" "$vtw_lock_file"
  trap - RETURN
}
