#!/bin/bash
# Build the NATIVE libghostty-vt archives for EVERY supported target from pinned
# source and publish them as prebuilt assets so ordinary contributors and CI
# never need zig. Run this whenever you change ghostty-vt-native.pin or
# ghostty-vt-native.patch.
#
#   make publish-native-vt        # or: ./scripts/publish-libghostty-vt.sh
#
# It, for each of ${VT_PLATFORMS[@]} (darwin/arm64 + linux/amd64 + linux/arm64):
# (1) cross-builds from source with zig (all targets build from one Mac);
# (2) packs a per-platform tarball keyed by pin+patch; (3) uploads it to the
# rolling `native-vt-prebuilts` GitHub release (creating the release if absent,
# clobbering a same-key asset). Then it rewrites ghostty-vt-native.lock with the
# shared key + one sha256 per platform. COMMIT the updated lock — the Makefile
# depends on it, so committing it is what makes everyone re-fetch.
#
# Requires: zig 0.16.x (cross-compiles all targets from one host), and `gh`
# authenticated with write access to the repo.
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/libghostty-vt.sh"

command -v gh >/dev/null || { echo "error: gh CLI required to publish" >&2; exit 1; }

key="$(vt_key)"
tmp="$(mktemp -d "${TMPDIR:-/tmp}/attn-vt-pub.XXXXXX")"
trap 'rm -rf "$tmp"' EXIT

# Ensure the rolling release exists before uploading the first asset.
if ! gh release view "$VT_RELEASE_TAG" --repo "$VT_REPO" >/dev/null 2>&1; then
  echo "==> creating release $VT_RELEASE_TAG"
  gh release create "$VT_RELEASE_TAG" --repo "$VT_REPO" \
    --title "Prebuilt libghostty-vt" \
    --notes "Prebuilt native libghostty-vt static libraries (darwin/arm64, linux/amd64, linux/arm64) keyed by ghostty pin + carried patch. Downloaded by scripts/build-libghostty-vt.sh; verified against ghostty-vt-native.lock. Do not delete assets — older commits still reference them."
fi

# Accumulate the per-platform sha256 lines for the lock file.
sha_lines=""
for platform in "${VT_PLATFORMS[@]}"; do
  echo "==> building libghostty-vt from source ($platform)"
  ATTN_VT_FROM_SOURCE=1 vt_build_from_source "$platform"

  asset="$(vt_asset_name_for "$platform")"
  echo "==> packing $asset"
  vt_pack "$tmp/$asset" "$platform"
  sha="$(shasum -a 256 "$tmp/$asset" | cut -d' ' -f1)"

  echo "==> uploading $asset to $VT_RELEASE_TAG"
  gh release upload "$VT_RELEASE_TAG" "$tmp/$asset" --repo "$VT_REPO" --clobber

  sha_lines+="sha256_${platform}=${sha}"$'\n'
  echo "    $platform sha256 $sha"
done

echo "==> writing $vt_lock_file"
{
  cat <<EOF
# Prebuilt libghostty-vt artifact lock. REGENERATED by make publish-native-vt;
# do not hand-edit. key = sha256(pin commit + carried patch), shared across
# platforms. Consumers download the per-platform asset named
# libghostty-vt-<key>-<goos>_<goarch>.tar.gz from the "$VT_RELEASE_TAG" release
# and verify it against sha256_<goos>_<goarch> before linking. See
# scripts/build-libghostty-vt.sh.
key=$key
EOF
  printf '%s' "$sha_lines"
} > "$vt_lock_file"

echo
echo "published ${#VT_PLATFORMS[@]} platform(s) for key $key"
echo "  commit ghostty-vt-native.lock to make everyone re-fetch."
