#!/bin/bash
# Build the NATIVE libghostty-vt archive from pinned source and publish it as a
# prebuilt asset so ordinary contributors never need zig. Run this whenever you
# change ghostty-vt-native.pin or ghostty-vt-native.patch.
#
#   make publish-native-vt        # or: ./scripts/publish-libghostty-vt.sh
#
# It: (1) builds from source (needs zig 0.16.x); (2) packs a tarball keyed by
# pin+patch; (3) uploads it to the rolling `native-vt-prebuilts` GitHub release
# (creating the release if absent, clobbering a same-key asset); (4) rewrites
# ghostty-vt-native.lock with the new key + sha256. COMMIT the updated lock —
# the Makefile depends on it, so committing it is what makes everyone re-fetch.
#
# Requires: zig 0.16.x, and `gh` authenticated with write access to the repo.
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/libghostty-vt.sh"

command -v gh >/dev/null || { echo "error: gh CLI required to publish" >&2; exit 1; }

echo "==> building libghostty-vt from source (publish)"
ATTN_VT_FROM_SOURCE=1 vt_build_from_source

key="$(vt_key)"
asset="$(vt_asset_name)"
tmp="$(mktemp -d "${TMPDIR:-/tmp}/attn-vt-pub.XXXXXX")"
trap 'rm -rf "$tmp"' EXIT

echo "==> packing $asset"
vt_pack "$tmp/$asset"
sha="$(shasum -a 256 "$tmp/$asset" | cut -d' ' -f1)"

# Ensure the rolling release exists.
if ! gh release view "$VT_RELEASE_TAG" --repo "$VT_REPO" >/dev/null 2>&1; then
  echo "==> creating release $VT_RELEASE_TAG"
  gh release create "$VT_RELEASE_TAG" --repo "$VT_REPO" \
    --title "Prebuilt libghostty-vt" \
    --notes "Prebuilt native libghostty-vt static libraries (Darwin/arm64) keyed by ghostty pin + carried patch. Downloaded by scripts/build-libghostty-vt.sh; verified against ghostty-vt-native.lock. Do not delete assets — older commits still reference them."
fi

echo "==> uploading $asset to $VT_RELEASE_TAG"
gh release upload "$VT_RELEASE_TAG" "$tmp/$asset" --repo "$VT_REPO" --clobber

echo "==> writing $vt_lock_file"
cat > "$vt_lock_file" <<EOF
# Prebuilt libghostty-vt artifact lock. REGENERATED by make publish-native-vt;
# do not hand-edit. key = sha256(pin commit + carried patch). Consumers download
# the asset named libghostty-vt-<key>.tar.gz from the "$VT_RELEASE_TAG" release
# and verify it against sha256 before linking. See scripts/build-libghostty-vt.sh.
key=$key
sha256=$sha
EOF

echo
echo "published: $asset"
echo "  key    : $key"
echo "  sha256 : $sha"
echo "  commit ghostty-vt-native.lock to make everyone re-fetch."
