// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package protocol

type AddCommentMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Content corresponds to the JSON schema field "content".
	Content string `json:"content"`

	// Filepath corresponds to the JSON schema field "filepath".
	Filepath string `json:"filepath"`

	// LineEnd corresponds to the JSON schema field "line_end".
	LineEnd int `json:"line_end"`

	// LineStart corresponds to the JSON schema field "line_start".
	LineStart int `json:"line_start"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`
}

type AddCommentResultMessage struct {
	// Comment corresponds to the JSON schema field "comment".
	Comment *ReviewComment `json:"comment,omitempty"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type ApprovePRMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Number corresponds to the JSON schema field "number".
	Number int `json:"number"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type Branch struct {
	// CommitHash corresponds to the JSON schema field "commit_hash".
	CommitHash *string `json:"commit_hash,omitempty"`

	// CommitTime corresponds to the JSON schema field "commit_time".
	CommitTime *string `json:"commit_time,omitempty"`

	// IsCurrent corresponds to the JSON schema field "is_current".
	IsCurrent *bool `json:"is_current,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`
}

type BranchDiffFile struct {
	// Additions corresponds to the JSON schema field "additions".
	Additions *int `json:"additions,omitempty"`

	// Deletions corresponds to the JSON schema field "deletions".
	Deletions *int `json:"deletions,omitempty"`

	// HasUncommitted corresponds to the JSON schema field "has_uncommitted".
	HasUncommitted *bool `json:"has_uncommitted,omitempty"`

	// OldPath corresponds to the JSON schema field "old_path".
	OldPath *string `json:"old_path,omitempty"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Status corresponds to the JSON schema field "status".
	Status string `json:"status"`
}

type BranchDiffFilesResultMessage struct {
	// BaseRef corresponds to the JSON schema field "base_ref".
	BaseRef string `json:"base_ref"`

	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Files corresponds to the JSON schema field "files".
	Files []BranchDiffFile `json:"files"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type BranchesResultMessage struct {
	// Branches corresponds to the JSON schema field "branches".
	Branches []Branch `json:"branches"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type CancelReviewMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`
}

type CheckAttnStashMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type CheckAttnStashResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Found corresponds to the JSON schema field "found".
	Found bool `json:"found"`

	// StashRef corresponds to the JSON schema field "stash_ref".
	StashRef *string `json:"stash_ref,omitempty"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type CheckDirtyMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type CheckDirtyResultMessage struct {
	// Dirty corresponds to the JSON schema field "dirty".
	Dirty bool `json:"dirty"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type ClearSessionsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`
}

type CollapseRepoMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Collapsed corresponds to the JSON schema field "collapsed".
	Collapsed bool `json:"collapsed"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type CommitWIPMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type CommitWIPResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type CreateBranchMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`
}

type CreateBranchResultMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type CreateWorktreeFromBranchMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty"`
}

type CreateWorktreeMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty"`

	// StartingFrom corresponds to the JSON schema field "starting_from".
	StartingFrom *string `json:"starting_from,omitempty"`
}

type CreateWorktreeResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type DeleteBranchMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Force corresponds to the JSON schema field "force".
	Force bool `json:"force"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`
}

type DeleteBranchResultMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type DeleteCommentMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// CommentID corresponds to the JSON schema field "comment_id".
	CommentID string `json:"comment_id"`
}

type DeleteCommentResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type DeleteWorktreeMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}

type DeleteWorktreeResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type FetchPRDetailsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type FetchRemotesMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type FetchRemotesResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type FileDiffResultMessage struct {
	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Modified corresponds to the JSON schema field "modified".
	Modified string `json:"modified"`

	// Original corresponds to the JSON schema field "original".
	Original string `json:"original"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type GetBranchDiffFilesMessage struct {
	// BaseRef corresponds to the JSON schema field "base_ref".
	BaseRef *string `json:"base_ref,omitempty"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`
}

type GetCommentsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Filepath corresponds to the JSON schema field "filepath".
	Filepath *string `json:"filepath,omitempty"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`
}

type GetCommentsResultMessage struct {
	// Comments corresponds to the JSON schema field "comments".
	Comments []ReviewComment `json:"comments,omitempty"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type GetDefaultBranchMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type GetDefaultBranchResultMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type GetFileDiffMessage struct {
	// BaseRef corresponds to the JSON schema field "base_ref".
	BaseRef *string `json:"base_ref,omitempty"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Staged corresponds to the JSON schema field "staged".
	Staged *bool `json:"staged,omitempty"`
}

type GetRecentLocationsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Limit corresponds to the JSON schema field "limit".
	Limit *int `json:"limit,omitempty"`
}

type GetRepoInfoMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type GetRepoInfoResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Info corresponds to the JSON schema field "info".
	Info *RepoInfo `json:"info,omitempty"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type GetReviewStateMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// RepoPath corresponds to the JSON schema field "repo_path".
	RepoPath string `json:"repo_path"`
}

type GetReviewStateResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// State corresponds to the JSON schema field "state".
	State *ReviewState `json:"state,omitempty"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type GetSettingsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`
}

type GitFileChange struct {
	// Additions corresponds to the JSON schema field "additions".
	Additions *int `json:"additions,omitempty"`

	// Deletions corresponds to the JSON schema field "deletions".
	Deletions *int `json:"deletions,omitempty"`

	// OldPath corresponds to the JSON schema field "old_path".
	OldPath *string `json:"old_path,omitempty"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Status corresponds to the JSON schema field "status".
	Status string `json:"status"`
}

type GitStatusUpdateMessage struct {
	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Staged corresponds to the JSON schema field "staged".
	Staged []GitFileChange `json:"staged"`

	// Unstaged corresponds to the JSON schema field "unstaged".
	Unstaged []GitFileChange `json:"unstaged"`

	// Untracked corresponds to the JSON schema field "untracked".
	Untracked []GitFileChange `json:"untracked"`
}

type HeartbeatMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type HeatState string

const HeatStateCold HeatState = "cold"
const HeatStateHot HeatState = "hot"
const HeatStateWarm HeatState = "warm"

type InjectTestPRMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// PR corresponds to the JSON schema field "pr".
	PR PR `json:"pr"`
}

type InjectTestSessionMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Session corresponds to the JSON schema field "session".
	Session Session `json:"session"`
}

type ListBranchesMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`
}

type ListRemoteBranchesMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type ListRemoteBranchesResultMessage struct {
	// Branches corresponds to the JSON schema field "branches".
	Branches []Branch `json:"branches"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type ListWorktreesMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`
}

type MarkFileViewedMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Filepath corresponds to the JSON schema field "filepath".
	Filepath string `json:"filepath"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`

	// Viewed corresponds to the JSON schema field "viewed".
	Viewed bool `json:"viewed"`
}

type MarkFileViewedResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Filepath corresponds to the JSON schema field "filepath".
	Filepath string `json:"filepath"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`

	// Viewed corresponds to the JSON schema field "viewed".
	Viewed bool `json:"viewed"`
}

type MergePRMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Method corresponds to the JSON schema field "method".
	Method string `json:"method"`

	// Number corresponds to the JSON schema field "number".
	Number int `json:"number"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type MuteMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type MuteOwnerMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Owner corresponds to the JSON schema field "owner".
	Owner string `json:"owner"`
}

type MutePRMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type MuteRepoMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type OwnerState struct {
	// Muted corresponds to the JSON schema field "muted".
	Muted bool `json:"muted"`

	// Owner corresponds to the JSON schema field "owner".
	Owner string `json:"owner"`
}

type PR struct {
	// ApprovedByMe corresponds to the JSON schema field "approved_by_me".
	ApprovedByMe bool `json:"approved_by_me"`

	// CIStatus corresponds to the JSON schema field "ci_status".
	CIStatus *string `json:"ci_status,omitempty"`

	// CommentCount corresponds to the JSON schema field "comment_count".
	CommentCount *int `json:"comment_count,omitempty"`

	// DetailsFetched corresponds to the JSON schema field "details_fetched".
	DetailsFetched bool `json:"details_fetched"`

	// DetailsFetchedAt corresponds to the JSON schema field "details_fetched_at".
	DetailsFetchedAt *string `json:"details_fetched_at,omitempty"`

	// HasNewChanges corresponds to the JSON schema field "has_new_changes".
	HasNewChanges bool `json:"has_new_changes"`

	// HeadBranch corresponds to the JSON schema field "head_branch".
	HeadBranch *string `json:"head_branch,omitempty"`

	// HeadSHA corresponds to the JSON schema field "head_sha".
	HeadSHA *string `json:"head_sha,omitempty"`

	// HeatState corresponds to the JSON schema field "heat_state".
	HeatState *HeatState `json:"heat_state,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// LastHeatActivityAt corresponds to the JSON schema field
	// "last_heat_activity_at".
	LastHeatActivityAt *string `json:"last_heat_activity_at,omitempty"`

	// LastPolled corresponds to the JSON schema field "last_polled".
	LastPolled string `json:"last_polled"`

	// LastUpdated corresponds to the JSON schema field "last_updated".
	LastUpdated string `json:"last_updated"`

	// Mergeable corresponds to the JSON schema field "mergeable".
	Mergeable *bool `json:"mergeable,omitempty"`

	// MergeableState corresponds to the JSON schema field "mergeable_state".
	MergeableState *string `json:"mergeable_state,omitempty"`

	// Muted corresponds to the JSON schema field "muted".
	Muted bool `json:"muted"`

	// Number corresponds to the JSON schema field "number".
	Number int `json:"number"`

	// Reason corresponds to the JSON schema field "reason".
	Reason string `json:"reason"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`

	// ReviewStatus corresponds to the JSON schema field "review_status".
	ReviewStatus *string `json:"review_status,omitempty"`

	// Role corresponds to the JSON schema field "role".
	Role PRRole `json:"role"`

	// State corresponds to the JSON schema field "state".
	State string `json:"state"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title"`

	// URL corresponds to the JSON schema field "url".
	URL string `json:"url"`
}

type PRActionResultMessage struct {
	// Action corresponds to the JSON schema field "action".
	Action string `json:"action"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Number corresponds to the JSON schema field "number".
	Number int `json:"number"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type PRRole string

const PRRoleAuthor PRRole = "author"
const PRRoleReviewer PRRole = "reviewer"

type PRVisitedMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type QueryMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Filter corresponds to the JSON schema field "filter".
	Filter *string `json:"filter,omitempty"`
}

type QueryOwnersMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Filter corresponds to the JSON schema field "filter".
	Filter *string `json:"filter,omitempty"`
}

type QueryPRsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Filter corresponds to the JSON schema field "filter".
	Filter *string `json:"filter,omitempty"`
}

type QueryReposMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Filter corresponds to the JSON schema field "filter".
	Filter *string `json:"filter,omitempty"`
}

type RateLimitedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ResetAt corresponds to the JSON schema field "reset_at".
	ResetAt string `json:"reset_at"`

	// Resource corresponds to the JSON schema field "resource".
	Resource string `json:"resource"`
}

type RecentLocation struct {
	// Label corresponds to the JSON schema field "label".
	Label string `json:"label"`

	// LastSeen corresponds to the JSON schema field "last_seen".
	LastSeen string `json:"last_seen"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// UseCount corresponds to the JSON schema field "use_count".
	UseCount int `json:"use_count"`
}

type RecentLocationsResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Locations corresponds to the JSON schema field "locations".
	Locations []RecentLocation `json:"locations"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type RecordString map[string]interface{}

type RefreshPRsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`
}

type RefreshPRsResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type RegisterMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Dir corresponds to the JSON schema field "dir".
	Dir string `json:"dir"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label,omitempty"`
}

type RepoInfo struct {
	// Branches corresponds to the JSON schema field "branches".
	Branches []Branch `json:"branches"`

	// CurrentBranch corresponds to the JSON schema field "current_branch".
	CurrentBranch string `json:"current_branch"`

	// CurrentCommitHash corresponds to the JSON schema field "current_commit_hash".
	CurrentCommitHash string `json:"current_commit_hash"`

	// CurrentCommitTime corresponds to the JSON schema field "current_commit_time".
	CurrentCommitTime string `json:"current_commit_time"`

	// DefaultBranch corresponds to the JSON schema field "default_branch".
	DefaultBranch string `json:"default_branch"`

	// FetchedAt corresponds to the JSON schema field "fetched_at".
	FetchedAt *string `json:"fetched_at,omitempty"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`

	// Worktrees corresponds to the JSON schema field "worktrees".
	Worktrees []Worktree `json:"worktrees"`
}

type RepoState struct {
	// Collapsed corresponds to the JSON schema field "collapsed".
	Collapsed bool `json:"collapsed"`

	// Muted corresponds to the JSON schema field "muted".
	Muted bool `json:"muted"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type ResolveCommentMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// CommentID corresponds to the JSON schema field "comment_id".
	CommentID string `json:"comment_id"`

	// Resolved corresponds to the JSON schema field "resolved".
	Resolved bool `json:"resolved"`
}

type ResolveCommentResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type Response struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Ok corresponds to the JSON schema field "ok".
	Ok bool `json:"ok"`

	// Owners corresponds to the JSON schema field "owners".
	Owners []OwnerState `json:"owners,omitempty"`

	// Prs corresponds to the JSON schema field "prs".
	Prs []PR `json:"prs,omitempty"`

	// Repos corresponds to the JSON schema field "repos".
	Repos []RepoState `json:"repos,omitempty"`

	// Sessions corresponds to the JSON schema field "sessions".
	Sessions []Session `json:"sessions,omitempty"`
}

type ReviewCancelledMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`
}

type ReviewChunkMessage struct {
	// Content corresponds to the JSON schema field "content".
	Content string `json:"content"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`
}

type ReviewComment struct {
	// Author corresponds to the JSON schema field "author".
	Author string `json:"author"`

	// Content corresponds to the JSON schema field "content".
	Content string `json:"content"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt string `json:"created_at"`

	// Filepath corresponds to the JSON schema field "filepath".
	Filepath string `json:"filepath"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// LineEnd corresponds to the JSON schema field "line_end".
	LineEnd int `json:"line_end"`

	// LineStart corresponds to the JSON schema field "line_start".
	LineStart int `json:"line_start"`

	// Resolved corresponds to the JSON schema field "resolved".
	Resolved bool `json:"resolved"`

	// ResolvedAt corresponds to the JSON schema field "resolved_at".
	ResolvedAt *string `json:"resolved_at,omitempty"`

	// ResolvedBy corresponds to the JSON schema field "resolved_by".
	ResolvedBy *string `json:"resolved_by,omitempty"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`

	// WontFix corresponds to the JSON schema field "wont_fix".
	WontFix bool `json:"wont_fix"`

	// WontFixAt corresponds to the JSON schema field "wont_fix_at".
	WontFixAt *string `json:"wont_fix_at,omitempty"`

	// WontFixBy corresponds to the JSON schema field "wont_fix_by".
	WontFixBy *string `json:"wont_fix_by,omitempty"`
}

type ReviewCompleteMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type ReviewFinding struct {
	// Content corresponds to the JSON schema field "content".
	Content string `json:"content"`

	// Filepath corresponds to the JSON schema field "filepath".
	Filepath string `json:"filepath"`

	// LineEnd corresponds to the JSON schema field "line_end".
	LineEnd int `json:"line_end"`

	// LineStart corresponds to the JSON schema field "line_start".
	LineStart int `json:"line_start"`

	// Severity corresponds to the JSON schema field "severity".
	Severity *string `json:"severity,omitempty"`
}

type ReviewFindingMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Finding corresponds to the JSON schema field "finding".
	Finding ReviewFinding `json:"finding"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`
}

type ReviewStartedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`
}

type ReviewState struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// RepoPath corresponds to the JSON schema field "repo_path".
	RepoPath string `json:"repo_path"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`

	// ViewedFiles corresponds to the JSON schema field "viewed_files".
	ViewedFiles []string `json:"viewed_files"`
}

type Session struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch *string `json:"branch,omitempty"`

	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// IsWorktree corresponds to the JSON schema field "is_worktree".
	IsWorktree *bool `json:"is_worktree,omitempty"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label"`

	// LastSeen corresponds to the JSON schema field "last_seen".
	LastSeen string `json:"last_seen"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo *string `json:"main_repo,omitempty"`

	// Muted corresponds to the JSON schema field "muted".
	Muted bool `json:"muted"`

	// State corresponds to the JSON schema field "state".
	State SessionState `json:"state"`

	// StateSince corresponds to the JSON schema field "state_since".
	StateSince string `json:"state_since"`

	// StateUpdatedAt corresponds to the JSON schema field "state_updated_at".
	StateUpdatedAt string `json:"state_updated_at"`

	// Todos corresponds to the JSON schema field "todos".
	Todos []string `json:"todos,omitempty"`
}

type SessionState string

const SessionStateIdle SessionState = "idle"
const SessionStateWaitingInput SessionState = "waiting_input"
const SessionStateWorking SessionState = "working"

type SetSettingMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Key corresponds to the JSON schema field "key".
	Key string `json:"key"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value"`
}

type StartReviewMessage struct {
	// BaseBranch corresponds to the JSON schema field "base_branch".
	BaseBranch string `json:"base_branch"`

	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// RepoPath corresponds to the JSON schema field "repo_path".
	RepoPath string `json:"repo_path"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`
}

type StashMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type StashPopMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type StashPopResultMessage struct {
	// Conflict corresponds to the JSON schema field "conflict".
	Conflict *bool `json:"conflict,omitempty"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type StashResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type StateMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// State corresponds to the JSON schema field "state".
	State string `json:"state"`
}

type StopMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// TranscriptPath corresponds to the JSON schema field "transcript_path".
	TranscriptPath string `json:"transcript_path"`
}

type SubscribeGitStatusMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`
}

type SwitchBranchMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`
}

type SwitchBranchResultMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type TodosMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Todos corresponds to the JSON schema field "todos".
	Todos []string `json:"todos"`
}

type UnregisterMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type UnsubscribeGitStatusMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`
}

type UpdateCommentMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// CommentID corresponds to the JSON schema field "comment_id".
	CommentID string `json:"comment_id"`

	// Content corresponds to the JSON schema field "content".
	Content string `json:"content"`
}

type UpdateCommentResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type WebSocketEvent struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch *string `json:"branch,omitempty"`

	// Branches corresponds to the JSON schema field "branches".
	Branches []Branch `json:"branches,omitempty"`

	// Conflict corresponds to the JSON schema field "conflict".
	Conflict *bool `json:"conflict,omitempty"`

	// Dirty corresponds to the JSON schema field "dirty".
	Dirty *bool `json:"dirty,omitempty"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Found corresponds to the JSON schema field "found".
	Found *bool `json:"found,omitempty"`

	// Owners corresponds to the JSON schema field "owners".
	Owners []OwnerState `json:"owners,omitempty"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion *string `json:"protocol_version,omitempty"`

	// Prs corresponds to the JSON schema field "prs".
	Prs []PR `json:"prs,omitempty"`

	// RateLimitResetAt corresponds to the JSON schema field "rate_limit_reset_at".
	RateLimitResetAt *string `json:"rate_limit_reset_at,omitempty"`

	// RateLimitResource corresponds to the JSON schema field "rate_limit_resource".
	RateLimitResource *string `json:"rate_limit_resource,omitempty"`

	// RecentLocations corresponds to the JSON schema field "recent_locations".
	RecentLocations []RecentLocation `json:"recent_locations,omitempty"`

	// Repos corresponds to the JSON schema field "repos".
	Repos []RepoState `json:"repos,omitempty"`

	// Session corresponds to the JSON schema field "session".
	Session *Session `json:"session,omitempty"`

	// Sessions corresponds to the JSON schema field "sessions".
	Sessions []Session `json:"sessions,omitempty"`

	// Settings corresponds to the JSON schema field "settings".
	Settings RecordString `json:"settings,omitempty"`

	// StashRef corresponds to the JSON schema field "stash_ref".
	StashRef *string `json:"stash_ref,omitempty"`

	// Success corresponds to the JSON schema field "success".
	Success *bool `json:"success,omitempty"`

	// Worktrees corresponds to the JSON schema field "worktrees".
	Worktrees []Worktree `json:"worktrees,omitempty"`
}

type WontFixCommentMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// CommentID corresponds to the JSON schema field "comment_id".
	CommentID string `json:"comment_id"`

	// WontFix corresponds to the JSON schema field "wont_fix".
	WontFix bool `json:"wont_fix"`
}

type WontFixCommentResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type Worktree struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt *string `json:"created_at,omitempty"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}

type WorktreeCreatedEvent struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}
