// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package protocol

type AddCommentMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Content corresponds to the JSON schema field "content".
	Content string `json:"content"`

	// Filepath corresponds to the JSON schema field "filepath".
	Filepath string `json:"filepath"`

	// LineEnd corresponds to the JSON schema field "line_end".
	LineEnd int `json:"line_end"`

	// LineStart corresponds to the JSON schema field "line_start".
	LineStart int `json:"line_start"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`
}

type AddCommentResultMessage struct {
	// Comment corresponds to the JSON schema field "comment".
	Comment *ReviewComment `json:"comment,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type AddEndpointMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// SshTarget corresponds to the JSON schema field "ssh_target".
	SshTarget string `json:"ssh_target"`
}

type AnswerReviewLoopMessage struct {
	// Answer corresponds to the JSON schema field "answer".
	Answer string `json:"answer"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// InteractionID corresponds to the JSON schema field "interaction_id".
	InteractionID *string `json:"interaction_id,omitempty,omitzero"`

	// LoopID corresponds to the JSON schema field "loop_id".
	LoopID string `json:"loop_id"`
}

type ApprovePRMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type AttachPolicy string

const AttachPolicyFreshSpawn AttachPolicy = "fresh_spawn"
const AttachPolicyRelaunchRestore AttachPolicy = "relaunch_restore"
const AttachPolicySameAppRemount AttachPolicy = "same_app_remount"

type AttachResultMessage struct {
	// Cols corresponds to the JSON schema field "cols".
	Cols *int `json:"cols,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// LastSeq corresponds to the JSON schema field "last_seq".
	LastSeq *int `json:"last_seq,omitempty,omitzero"`

	// Pid corresponds to the JSON schema field "pid".
	Pid *int `json:"pid,omitempty,omitzero"`

	// ReplaySegments corresponds to the JSON schema field "replay_segments".
	ReplaySegments []ReplaySegment `json:"replay_segments,omitempty,omitzero"`

	// Rows corresponds to the JSON schema field "rows".
	Rows *int `json:"rows,omitempty,omitzero"`

	// Running corresponds to the JSON schema field "running".
	Running *bool `json:"running,omitempty,omitzero"`

	// ScreenCols corresponds to the JSON schema field "screen_cols".
	ScreenCols *int `json:"screen_cols,omitempty,omitzero"`

	// ScreenCursorVisible corresponds to the JSON schema field
	// "screen_cursor_visible".
	ScreenCursorVisible *bool `json:"screen_cursor_visible,omitempty,omitzero"`

	// ScreenCursorX corresponds to the JSON schema field "screen_cursor_x".
	ScreenCursorX *int `json:"screen_cursor_x,omitempty,omitzero"`

	// ScreenCursorY corresponds to the JSON schema field "screen_cursor_y".
	ScreenCursorY *int `json:"screen_cursor_y,omitempty,omitzero"`

	// ScreenRows corresponds to the JSON schema field "screen_rows".
	ScreenRows *int `json:"screen_rows,omitempty,omitzero"`

	// ScreenSnapshot corresponds to the JSON schema field "screen_snapshot".
	ScreenSnapshot *string `json:"screen_snapshot,omitempty,omitzero"`

	// ScreenSnapshotFresh corresponds to the JSON schema field
	// "screen_snapshot_fresh".
	ScreenSnapshotFresh *bool `json:"screen_snapshot_fresh,omitempty,omitzero"`

	// Scrollback corresponds to the JSON schema field "scrollback".
	Scrollback *string `json:"scrollback,omitempty,omitzero"`

	// ScrollbackTruncated corresponds to the JSON schema field
	// "scrollback_truncated".
	ScrollbackTruncated *bool `json:"scrollback_truncated,omitempty,omitzero"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type AttachSessionMessage struct {
	// AttachPolicy corresponds to the JSON schema field "attach_policy".
	AttachPolicy *AttachPolicy `json:"attach_policy,omitempty,omitzero"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type AuthorState struct {
	// Author corresponds to the JSON schema field "author".
	Author string `json:"author"`

	// Muted corresponds to the JSON schema field "muted".
	Muted bool `json:"muted"`
}

type AuthorsUpdatedMessage struct {
	// Authors corresponds to the JSON schema field "authors".
	Authors []AuthorState `json:"authors,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`
}

type BootstrapEndpointMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID string `json:"endpoint_id"`
}

type Branch struct {
	// CommitHash corresponds to the JSON schema field "commit_hash".
	CommitHash *string `json:"commit_hash,omitempty,omitzero"`

	// CommitTime corresponds to the JSON schema field "commit_time".
	CommitTime *string `json:"commit_time,omitempty,omitzero"`

	// IsCurrent corresponds to the JSON schema field "is_current".
	IsCurrent *bool `json:"is_current,omitempty,omitzero"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`
}

type BranchChangedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Session corresponds to the JSON schema field "session".
	Session *Session `json:"session,omitempty,omitzero"`
}

type BranchDiffFile struct {
	// Additions corresponds to the JSON schema field "additions".
	Additions *int `json:"additions,omitempty,omitzero"`

	// Deletions corresponds to the JSON schema field "deletions".
	Deletions *int `json:"deletions,omitempty,omitzero"`

	// HasUncommitted corresponds to the JSON schema field "has_uncommitted".
	HasUncommitted *bool `json:"has_uncommitted,omitempty,omitzero"`

	// OldPath corresponds to the JSON schema field "old_path".
	OldPath *string `json:"old_path,omitempty,omitzero"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Status corresponds to the JSON schema field "status".
	Status string `json:"status"`
}

type BranchDiffFilesResultMessage struct {
	// BaseRef corresponds to the JSON schema field "base_ref".
	BaseRef string `json:"base_ref"`

	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Files corresponds to the JSON schema field "files".
	Files []BranchDiffFile `json:"files"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type BranchesResultMessage struct {
	// Branches corresponds to the JSON schema field "branches".
	Branches []Branch `json:"branches"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type BrowseDirectoryMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID *string `json:"endpoint_id,omitempty,omitzero"`

	// InputPath corresponds to the JSON schema field "input_path".
	InputPath string `json:"input_path"`

	// RequestID corresponds to the JSON schema field "request_id".
	RequestID *string `json:"request_id,omitempty,omitzero"`
}

type BrowseDirectoryResultMessage struct {
	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`

	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID *string `json:"endpoint_id,omitempty,omitzero"`

	// Entries corresponds to the JSON schema field "entries".
	Entries []DirectoryEntry `json:"entries"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// HomePath corresponds to the JSON schema field "home_path".
	HomePath *string `json:"home_path,omitempty,omitzero"`

	// InputPath corresponds to the JSON schema field "input_path".
	InputPath string `json:"input_path"`

	// RequestID corresponds to the JSON schema field "request_id".
	RequestID *string `json:"request_id,omitempty,omitzero"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type ClearSessionsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`
}

type ClearWarningsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`
}

type CollapseRepoMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Collapsed corresponds to the JSON schema field "collapsed".
	Collapsed bool `json:"collapsed"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type CommandErrorMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd *string `json:"cmd,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error string `json:"error"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type CreateWorktreeFromBranchMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty,omitzero"`
}

type CreateWorktreeMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID *string `json:"endpoint_id,omitempty,omitzero"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty,omitzero"`

	// StartingFrom corresponds to the JSON schema field "starting_from".
	StartingFrom *string `json:"starting_from,omitempty,omitzero"`
}

type CreateWorktreeResultMessage struct {
	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID *string `json:"endpoint_id,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty,omitzero"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type DaemonWarning struct {
	// Code corresponds to the JSON schema field "code".
	Code string `json:"code"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`
}

type DeleteCommentMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// CommentID corresponds to the JSON schema field "comment_id".
	CommentID string `json:"comment_id"`
}

type DeleteCommentResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type DeleteWorktreeMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID *string `json:"endpoint_id,omitempty,omitzero"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}

type DeleteWorktreeResultMessage struct {
	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID *string `json:"endpoint_id,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type DetachSessionMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type DirectoryEntry struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}

type EndpointActionResultMessage struct {
	// Action corresponds to the JSON schema field "action".
	Action string `json:"action"`

	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID *string `json:"endpoint_id,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type EndpointCapabilities struct {
	// AgentsAvailable corresponds to the JSON schema field "agents_available".
	AgentsAvailable []string `json:"agents_available"`

	// DaemonInstanceID corresponds to the JSON schema field "daemon_instance_id".
	DaemonInstanceID *string `json:"daemon_instance_id,omitempty,omitzero"`

	// ProjectsDirectory corresponds to the JSON schema field "projects_directory".
	ProjectsDirectory *string `json:"projects_directory,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion string `json:"protocol_version"`

	// PtyBackendMode corresponds to the JSON schema field "pty_backend_mode".
	PtyBackendMode *string `json:"pty_backend_mode,omitempty,omitzero"`

	// TailscaleAuthURL corresponds to the JSON schema field "tailscale_auth_url".
	TailscaleAuthURL *string `json:"tailscale_auth_url,omitempty,omitzero"`

	// TailscaleDomain corresponds to the JSON schema field "tailscale_domain".
	TailscaleDomain *string `json:"tailscale_domain,omitempty,omitzero"`

	// TailscaleEnabled corresponds to the JSON schema field "tailscale_enabled".
	TailscaleEnabled *bool `json:"tailscale_enabled,omitempty,omitzero"`

	// TailscaleError corresponds to the JSON schema field "tailscale_error".
	TailscaleError *string `json:"tailscale_error,omitempty,omitzero"`

	// TailscaleStatus corresponds to the JSON schema field "tailscale_status".
	TailscaleStatus *string `json:"tailscale_status,omitempty,omitzero"`

	// TailscaleURL corresponds to the JSON schema field "tailscale_url".
	TailscaleURL *string `json:"tailscale_url,omitempty,omitzero"`
}

type EndpointInfo struct {
	// Capabilities corresponds to the JSON schema field "capabilities".
	Capabilities *EndpointCapabilities `json:"capabilities,omitempty,omitzero"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty,omitzero"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// SessionCount corresponds to the JSON schema field "session_count".
	SessionCount *int `json:"session_count,omitempty,omitzero"`

	// SshTarget corresponds to the JSON schema field "ssh_target".
	SshTarget string `json:"ssh_target"`

	// Status corresponds to the JSON schema field "status".
	Status string `json:"status"`

	// StatusMessage corresponds to the JSON schema field "status_message".
	StatusMessage *string `json:"status_message,omitempty,omitzero"`
}

type EndpointStatusChangedMessage struct {
	// Endpoint corresponds to the JSON schema field "endpoint".
	Endpoint EndpointInfo `json:"endpoint"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`
}

type EndpointsUpdatedMessage struct {
	// Endpoints corresponds to the JSON schema field "endpoints".
	Endpoints []EndpointInfo `json:"endpoints"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`
}

type EnsureRepoMessage struct {
	// CloneURL corresponds to the JSON schema field "clone_url".
	CloneURL string `json:"clone_url"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// TargetPath corresponds to the JSON schema field "target_path".
	TargetPath string `json:"target_path"`
}

type EnsureRepoResultMessage struct {
	// Cloned corresponds to the JSON schema field "cloned".
	Cloned *bool `json:"cloned,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success *bool `json:"success,omitempty,omitzero"`

	// TargetPath corresponds to the JSON schema field "target_path".
	TargetPath *string `json:"target_path,omitempty,omitzero"`
}

type FetchPRDetailsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type FetchPRDetailsResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Prs corresponds to the JSON schema field "prs".
	Prs []PR `json:"prs,omitempty,omitzero"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type FetchRemotesMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type FetchRemotesResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type FileDiffResultMessage struct {
	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Modified corresponds to the JSON schema field "modified".
	Modified string `json:"modified"`

	// Original corresponds to the JSON schema field "original".
	Original string `json:"original"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type GetBranchDiffFilesMessage struct {
	// BaseRef corresponds to the JSON schema field "base_ref".
	BaseRef *string `json:"base_ref,omitempty,omitzero"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`
}

type GetCommentsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Filepath corresponds to the JSON schema field "filepath".
	Filepath *string `json:"filepath,omitempty,omitzero"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`
}

type GetCommentsResultMessage struct {
	// Comments corresponds to the JSON schema field "comments".
	Comments []ReviewComment `json:"comments,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type GetDefaultBranchMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type GetDefaultBranchResultMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type GetFileDiffMessage struct {
	// BaseRef corresponds to the JSON schema field "base_ref".
	BaseRef *string `json:"base_ref,omitempty,omitzero"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Staged corresponds to the JSON schema field "staged".
	Staged *bool `json:"staged,omitempty,omitzero"`
}

type GetRecentLocationsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID *string `json:"endpoint_id,omitempty,omitzero"`

	// Limit corresponds to the JSON schema field "limit".
	Limit *int `json:"limit,omitempty,omitzero"`

	// RequestID corresponds to the JSON schema field "request_id".
	RequestID *string `json:"request_id,omitempty,omitzero"`
}

type GetRepoInfoMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID *string `json:"endpoint_id,omitempty,omitzero"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type GetRepoInfoResultMessage struct {
	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID *string `json:"endpoint_id,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Info corresponds to the JSON schema field "info".
	Info *RepoInfo `json:"info,omitempty,omitzero"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type GetReviewLoopRunMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// LoopID corresponds to the JSON schema field "loop_id".
	LoopID string `json:"loop_id"`
}

type GetReviewLoopStateMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`
}

type GetReviewStateMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// RepoPath corresponds to the JSON schema field "repo_path".
	RepoPath string `json:"repo_path"`
}

type GetReviewStateResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// State corresponds to the JSON schema field "state".
	State *ReviewState `json:"state,omitempty,omitzero"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type GetSettingsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`
}

type GitFileChange struct {
	// Additions corresponds to the JSON schema field "additions".
	Additions *int `json:"additions,omitempty,omitzero"`

	// Deletions corresponds to the JSON schema field "deletions".
	Deletions *int `json:"deletions,omitempty,omitzero"`

	// OldPath corresponds to the JSON schema field "old_path".
	OldPath *string `json:"old_path,omitempty,omitzero"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Status corresponds to the JSON schema field "status".
	Status string `json:"status"`
}

type GitStatusUpdateMessage struct {
	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Staged corresponds to the JSON schema field "staged".
	Staged []GitFileChange `json:"staged"`

	// Unstaged corresponds to the JSON schema field "unstaged".
	Unstaged []GitFileChange `json:"unstaged"`

	// Untracked corresponds to the JSON schema field "untracked".
	Untracked []GitFileChange `json:"untracked"`
}

type HeartbeatMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type HeatState string

const HeatStateCold HeatState = "cold"
const HeatStateHot HeatState = "hot"
const HeatStateWarm HeatState = "warm"

type InitialStateMessage struct {
	// Authors corresponds to the JSON schema field "authors".
	Authors []AuthorState `json:"authors,omitempty,omitzero"`

	// DaemonInstanceID corresponds to the JSON schema field "daemon_instance_id".
	DaemonInstanceID *string `json:"daemon_instance_id,omitempty,omitzero"`

	// Endpoints corresponds to the JSON schema field "endpoints".
	Endpoints []EndpointInfo `json:"endpoints,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion *string `json:"protocol_version,omitempty,omitzero"`

	// Prs corresponds to the JSON schema field "prs".
	Prs []PR `json:"prs,omitempty,omitzero"`

	// Repos corresponds to the JSON schema field "repos".
	Repos []RepoState `json:"repos,omitempty,omitzero"`

	// Sessions corresponds to the JSON schema field "sessions".
	Sessions []Session `json:"sessions,omitempty,omitzero"`

	// Settings corresponds to the JSON schema field "settings".
	Settings RecordString `json:"settings,omitempty,omitzero"`

	// SourceFingerprint corresponds to the JSON schema field "source_fingerprint".
	SourceFingerprint *string `json:"source_fingerprint,omitempty,omitzero"`

	// Warnings corresponds to the JSON schema field "warnings".
	Warnings []DaemonWarning `json:"warnings,omitempty,omitzero"`

	// Workspaces corresponds to the JSON schema field "workspaces".
	Workspaces []WorkspaceSnapshot `json:"workspaces,omitempty,omitzero"`
}

type InjectTestPRMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// PR corresponds to the JSON schema field "pr".
	PR PR `json:"pr"`
}

type InjectTestSessionMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Session corresponds to the JSON schema field "session".
	Session Session `json:"session"`
}

type InspectPathMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID *string `json:"endpoint_id,omitempty,omitzero"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// RequestID corresponds to the JSON schema field "request_id".
	RequestID *string `json:"request_id,omitempty,omitzero"`
}

type InspectPathResultMessage struct {
	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID *string `json:"endpoint_id,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Inspection corresponds to the JSON schema field "inspection".
	Inspection *PathInspection `json:"inspection,omitempty,omitzero"`

	// RequestID corresponds to the JSON schema field "request_id".
	RequestID *string `json:"request_id,omitempty,omitzero"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type KillSessionMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Signal corresponds to the JSON schema field "signal".
	Signal *string `json:"signal,omitempty,omitzero"`
}

type ListBranchesMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`
}

type ListEndpointsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`
}

type ListRemoteBranchesMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type ListRemoteBranchesResultMessage struct {
	// Branches corresponds to the JSON schema field "branches".
	Branches []Branch `json:"branches"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type ListWorktreesMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`
}

type MarkFileViewedMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Filepath corresponds to the JSON schema field "filepath".
	Filepath string `json:"filepath"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`

	// Viewed corresponds to the JSON schema field "viewed".
	Viewed bool `json:"viewed"`
}

type MarkFileViewedResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Filepath corresponds to the JSON schema field "filepath".
	Filepath string `json:"filepath"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`

	// Viewed corresponds to the JSON schema field "viewed".
	Viewed bool `json:"viewed"`
}

type MergePRMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Method corresponds to the JSON schema field "method".
	Method string `json:"method"`
}

type MuteAuthorMessage struct {
	// Author corresponds to the JSON schema field "author".
	Author string `json:"author"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`
}

type MuteMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type MutePRMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type MuteRepoMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type PR struct {
	// ApprovedByMe corresponds to the JSON schema field "approved_by_me".
	ApprovedByMe bool `json:"approved_by_me"`

	// Author corresponds to the JSON schema field "author".
	Author string `json:"author"`

	// CIStatus corresponds to the JSON schema field "ci_status".
	CIStatus *string `json:"ci_status,omitempty,omitzero"`

	// CommentCount corresponds to the JSON schema field "comment_count".
	CommentCount *int `json:"comment_count,omitempty,omitzero"`

	// DetailsFetched corresponds to the JSON schema field "details_fetched".
	DetailsFetched bool `json:"details_fetched"`

	// DetailsFetchedAt corresponds to the JSON schema field "details_fetched_at".
	DetailsFetchedAt *string `json:"details_fetched_at,omitempty,omitzero"`

	// HasNewChanges corresponds to the JSON schema field "has_new_changes".
	HasNewChanges bool `json:"has_new_changes"`

	// HeadBranch corresponds to the JSON schema field "head_branch".
	HeadBranch *string `json:"head_branch,omitempty,omitzero"`

	// HeadSHA corresponds to the JSON schema field "head_sha".
	HeadSHA *string `json:"head_sha,omitempty,omitzero"`

	// HeatState corresponds to the JSON schema field "heat_state".
	HeatState *HeatState `json:"heat_state,omitempty,omitzero"`

	// Host corresponds to the JSON schema field "host".
	Host string `json:"host"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// LastHeatActivityAt corresponds to the JSON schema field
	// "last_heat_activity_at".
	LastHeatActivityAt *string `json:"last_heat_activity_at,omitempty,omitzero"`

	// LastPolled corresponds to the JSON schema field "last_polled".
	LastPolled string `json:"last_polled"`

	// LastUpdated corresponds to the JSON schema field "last_updated".
	LastUpdated string `json:"last_updated"`

	// Mergeable corresponds to the JSON schema field "mergeable".
	Mergeable *bool `json:"mergeable,omitempty,omitzero"`

	// MergeableState corresponds to the JSON schema field "mergeable_state".
	MergeableState *string `json:"mergeable_state,omitempty,omitzero"`

	// Muted corresponds to the JSON schema field "muted".
	Muted bool `json:"muted"`

	// Number corresponds to the JSON schema field "number".
	Number int `json:"number"`

	// Reason corresponds to the JSON schema field "reason".
	Reason string `json:"reason"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`

	// ReviewStatus corresponds to the JSON schema field "review_status".
	ReviewStatus *string `json:"review_status,omitempty,omitzero"`

	// Role corresponds to the JSON schema field "role".
	Role PRRole `json:"role"`

	// State corresponds to the JSON schema field "state".
	State string `json:"state"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title"`

	// URL corresponds to the JSON schema field "url".
	URL string `json:"url"`
}

type PRActionResultMessage struct {
	// Action corresponds to the JSON schema field "action".
	Action string `json:"action"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type PRRole string

const PRRoleAuthor PRRole = "author"
const PRRoleReviewer PRRole = "reviewer"

type PRVisitedMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type PRsUpdatedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Prs corresponds to the JSON schema field "prs".
	Prs []PR `json:"prs,omitempty,omitzero"`
}

type PathInspection struct {
	// Exists corresponds to the JSON schema field "exists".
	Exists bool `json:"exists"`

	// HomePath corresponds to the JSON schema field "home_path".
	HomePath *string `json:"home_path,omitempty,omitzero"`

	// InputPath corresponds to the JSON schema field "input_path".
	InputPath string `json:"input_path"`

	// IsDirectory corresponds to the JSON schema field "is_directory".
	IsDirectory bool `json:"is_directory"`

	// RepoRoot corresponds to the JSON schema field "repo_root".
	RepoRoot *string `json:"repo_root,omitempty,omitzero"`

	// ResolvedPath corresponds to the JSON schema field "resolved_path".
	ResolvedPath string `json:"resolved_path"`
}

type PtyDesyncMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Reason corresponds to the JSON schema field "reason".
	Reason string `json:"reason"`
}

type PtyInputMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Data corresponds to the JSON schema field "data".
	Data string `json:"data"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Source corresponds to the JSON schema field "source".
	Source *string `json:"source,omitempty,omitzero"`
}

type PtyOutputMessage struct {
	// Data corresponds to the JSON schema field "data".
	Data string `json:"data"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Seq corresponds to the JSON schema field "seq".
	Seq int `json:"seq"`
}

type PtyResizeMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Cols corresponds to the JSON schema field "cols".
	Cols int `json:"cols"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Rows corresponds to the JSON schema field "rows".
	Rows int `json:"rows"`
}

type PtyResizedMessage struct {
	// Cols corresponds to the JSON schema field "cols".
	Cols int `json:"cols"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Rows corresponds to the JSON schema field "rows".
	Rows int `json:"rows"`
}

type QueryAuthorsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`
}

type QueryMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Filter corresponds to the JSON schema field "filter".
	Filter *string `json:"filter,omitempty,omitzero"`
}

type QueryPRsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Filter corresponds to the JSON schema field "filter".
	Filter *string `json:"filter,omitempty,omitzero"`
}

type QueryReposMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Filter corresponds to the JSON schema field "filter".
	Filter *string `json:"filter,omitempty,omitzero"`
}

type RateLimitedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// RateLimitResetAt corresponds to the JSON schema field "rate_limit_reset_at".
	RateLimitResetAt string `json:"rate_limit_reset_at"`

	// RateLimitResource corresponds to the JSON schema field "rate_limit_resource".
	RateLimitResource string `json:"rate_limit_resource"`
}

type RecentLocation struct {
	// Label corresponds to the JSON schema field "label".
	Label string `json:"label"`

	// LastSeen corresponds to the JSON schema field "last_seen".
	LastSeen string `json:"last_seen"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// UseCount corresponds to the JSON schema field "use_count".
	UseCount int `json:"use_count"`
}

type RecentLocationsResultMessage struct {
	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID *string `json:"endpoint_id,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// HomePath corresponds to the JSON schema field "home_path".
	HomePath *string `json:"home_path,omitempty,omitzero"`

	// RecentLocations corresponds to the JSON schema field "recent_locations".
	RecentLocations []RecentLocation `json:"recent_locations"`

	// RequestID corresponds to the JSON schema field "request_id".
	RequestID *string `json:"request_id,omitempty,omitzero"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type RecordString map[string]interface{}

type RefreshPRsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`
}

type RefreshPRsResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type RegisterMessage struct {
	// Agent corresponds to the JSON schema field "agent".
	Agent *SessionAgent `json:"agent,omitempty,omitzero"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Dir corresponds to the JSON schema field "dir".
	Dir string `json:"dir"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label,omitempty,omitzero"`
}

type RemoveEndpointMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID string `json:"endpoint_id"`
}

type ReplaySegment struct {
	// Cols corresponds to the JSON schema field "cols".
	Cols int `json:"cols"`

	// Data corresponds to the JSON schema field "data".
	Data string `json:"data"`

	// Rows corresponds to the JSON schema field "rows".
	Rows int `json:"rows"`
}

type RepoInfo struct {
	// Branches corresponds to the JSON schema field "branches".
	Branches []Branch `json:"branches"`

	// CurrentBranch corresponds to the JSON schema field "current_branch".
	CurrentBranch string `json:"current_branch"`

	// CurrentCommitHash corresponds to the JSON schema field "current_commit_hash".
	CurrentCommitHash string `json:"current_commit_hash"`

	// CurrentCommitTime corresponds to the JSON schema field "current_commit_time".
	CurrentCommitTime string `json:"current_commit_time"`

	// DefaultBranch corresponds to the JSON schema field "default_branch".
	DefaultBranch string `json:"default_branch"`

	// FetchedAt corresponds to the JSON schema field "fetched_at".
	FetchedAt *string `json:"fetched_at,omitempty,omitzero"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`

	// Worktrees corresponds to the JSON schema field "worktrees".
	Worktrees []Worktree `json:"worktrees"`
}

type RepoState struct {
	// Collapsed corresponds to the JSON schema field "collapsed".
	Collapsed bool `json:"collapsed"`

	// Muted corresponds to the JSON schema field "muted".
	Muted bool `json:"muted"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type ReposUpdatedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Repos corresponds to the JSON schema field "repos".
	Repos []RepoState `json:"repos,omitempty,omitzero"`
}

type ResolveCommentMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// CommentID corresponds to the JSON schema field "comment_id".
	CommentID string `json:"comment_id"`

	// Resolved corresponds to the JSON schema field "resolved".
	Resolved bool `json:"resolved"`
}

type ResolveCommentResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type Response struct {
	// Authors corresponds to the JSON schema field "authors".
	Authors []AuthorState `json:"authors,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Ok corresponds to the JSON schema field "ok".
	Ok bool `json:"ok"`

	// Prs corresponds to the JSON schema field "prs".
	Prs []PR `json:"prs,omitempty,omitzero"`

	// Repos corresponds to the JSON schema field "repos".
	Repos []RepoState `json:"repos,omitempty,omitzero"`

	// ReviewLoopRun corresponds to the JSON schema field "review_loop_run".
	ReviewLoopRun *ReviewLoopRun `json:"review_loop_run,omitempty,omitzero"`

	// Sessions corresponds to the JSON schema field "sessions".
	Sessions []Session `json:"sessions,omitempty,omitzero"`

	// Workspaces corresponds to the JSON schema field "workspaces".
	Workspaces []WorkspaceSnapshot `json:"workspaces,omitempty,omitzero"`
}

type ReviewComment struct {
	// Author corresponds to the JSON schema field "author".
	Author string `json:"author"`

	// Content corresponds to the JSON schema field "content".
	Content string `json:"content"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt string `json:"created_at"`

	// Filepath corresponds to the JSON schema field "filepath".
	Filepath string `json:"filepath"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// LineEnd corresponds to the JSON schema field "line_end".
	LineEnd int `json:"line_end"`

	// LineStart corresponds to the JSON schema field "line_start".
	LineStart int `json:"line_start"`

	// Resolved corresponds to the JSON schema field "resolved".
	Resolved bool `json:"resolved"`

	// ResolvedAt corresponds to the JSON schema field "resolved_at".
	ResolvedAt *string `json:"resolved_at,omitempty,omitzero"`

	// ResolvedBy corresponds to the JSON schema field "resolved_by".
	ResolvedBy *string `json:"resolved_by,omitempty,omitzero"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`

	// WontFix corresponds to the JSON schema field "wont_fix".
	WontFix bool `json:"wont_fix"`

	// WontFixAt corresponds to the JSON schema field "wont_fix_at".
	WontFixAt *string `json:"wont_fix_at,omitempty,omitzero"`

	// WontFixBy corresponds to the JSON schema field "wont_fix_by".
	WontFixBy *string `json:"wont_fix_by,omitempty,omitzero"`
}

type ReviewLoopDecision string

const ReviewLoopDecisionContinue ReviewLoopDecision = "continue"
const ReviewLoopDecisionConverged ReviewLoopDecision = "converged"
const ReviewLoopDecisionError ReviewLoopDecision = "error"
const ReviewLoopDecisionNeedsUserInput ReviewLoopDecision = "needs_user_input"

type ReviewLoopInteraction struct {
	// Answer corresponds to the JSON schema field "answer".
	Answer *string `json:"answer,omitempty,omitzero"`

	// AnsweredAt corresponds to the JSON schema field "answered_at".
	AnsweredAt *string `json:"answered_at,omitempty,omitzero"`

	// ConsumedAt corresponds to the JSON schema field "consumed_at".
	ConsumedAt *string `json:"consumed_at,omitempty,omitzero"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt string `json:"created_at"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// IterationID corresponds to the JSON schema field "iteration_id".
	IterationID *string `json:"iteration_id,omitempty,omitzero"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind"`

	// LoopID corresponds to the JSON schema field "loop_id".
	LoopID string `json:"loop_id"`

	// Question corresponds to the JSON schema field "question".
	Question string `json:"question"`

	// Status corresponds to the JSON schema field "status".
	Status ReviewLoopInteractionStatus `json:"status"`
}

type ReviewLoopInteractionStatus string

const ReviewLoopInteractionStatusAnswered ReviewLoopInteractionStatus = "answered"
const ReviewLoopInteractionStatusConsumed ReviewLoopInteractionStatus = "consumed"
const ReviewLoopInteractionStatusPending ReviewLoopInteractionStatus = "pending"

type ReviewLoopIteration struct {
	// AssistantTraceJson corresponds to the JSON schema field "assistant_trace_json".
	AssistantTraceJson *string `json:"assistant_trace_json,omitempty,omitzero"`

	// BlockingReason corresponds to the JSON schema field "blocking_reason".
	BlockingReason *string `json:"blocking_reason,omitempty,omitzero"`

	// ChangeStats corresponds to the JSON schema field "change_stats".
	ChangeStats []BranchDiffFile `json:"change_stats,omitempty,omitzero"`

	// ChangesMade corresponds to the JSON schema field "changes_made".
	ChangesMade *bool `json:"changes_made,omitempty,omitzero"`

	// CompletedAt corresponds to the JSON schema field "completed_at".
	CompletedAt *string `json:"completed_at,omitempty,omitzero"`

	// Decision corresponds to the JSON schema field "decision".
	Decision *ReviewLoopDecision `json:"decision,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// FilesTouched corresponds to the JSON schema field "files_touched".
	FilesTouched []string `json:"files_touched,omitempty,omitzero"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// IterationNumber corresponds to the JSON schema field "iteration_number".
	IterationNumber int `json:"iteration_number"`

	// LoopID corresponds to the JSON schema field "loop_id".
	LoopID string `json:"loop_id"`

	// ResultText corresponds to the JSON schema field "result_text".
	ResultText *string `json:"result_text,omitempty,omitzero"`

	// StartedAt corresponds to the JSON schema field "started_at".
	StartedAt string `json:"started_at"`

	// Status corresponds to the JSON schema field "status".
	Status ReviewLoopIterationStatus `json:"status"`

	// StructuredOutputJson corresponds to the JSON schema field
	// "structured_output_json".
	StructuredOutputJson *string `json:"structured_output_json,omitempty,omitzero"`

	// SuggestedNextFocus corresponds to the JSON schema field "suggested_next_focus".
	SuggestedNextFocus *string `json:"suggested_next_focus,omitempty,omitzero"`

	// Summary corresponds to the JSON schema field "summary".
	Summary *string `json:"summary,omitempty,omitzero"`
}

type ReviewLoopIterationStatus string

const ReviewLoopIterationStatusAwaitingUser ReviewLoopIterationStatus = "awaiting_user"
const ReviewLoopIterationStatusCancelled ReviewLoopIterationStatus = "cancelled"
const ReviewLoopIterationStatusCompleted ReviewLoopIterationStatus = "completed"
const ReviewLoopIterationStatusError ReviewLoopIterationStatus = "error"
const ReviewLoopIterationStatusRunning ReviewLoopIterationStatus = "running"

type ReviewLoopResultMessage struct {
	// Action corresponds to the JSON schema field "action".
	Action string `json:"action"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// LoopID corresponds to the JSON schema field "loop_id".
	LoopID *string `json:"loop_id,omitempty,omitzero"`

	// ReviewLoopRun corresponds to the JSON schema field "review_loop_run".
	ReviewLoopRun *ReviewLoopRun `json:"review_loop_run,omitempty,omitzero"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type ReviewLoopRun struct {
	// CompletedAt corresponds to the JSON schema field "completed_at".
	CompletedAt *string `json:"completed_at,omitempty,omitzero"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt string `json:"created_at"`

	// CustomPrompt corresponds to the JSON schema field "custom_prompt".
	CustomPrompt *string `json:"custom_prompt,omitempty,omitzero"`

	// HandoffPayloadJson corresponds to the JSON schema field "handoff_payload_json".
	HandoffPayloadJson *string `json:"handoff_payload_json,omitempty,omitzero"`

	// IterationCount corresponds to the JSON schema field "iteration_count".
	IterationCount int `json:"iteration_count"`

	// IterationLimit corresponds to the JSON schema field "iteration_limit".
	IterationLimit int `json:"iteration_limit"`

	// Iterations corresponds to the JSON schema field "iterations".
	Iterations []ReviewLoopIteration `json:"iterations,omitempty,omitzero"`

	// LastDecision corresponds to the JSON schema field "last_decision".
	LastDecision *ReviewLoopDecision `json:"last_decision,omitempty,omitzero"`

	// LastError corresponds to the JSON schema field "last_error".
	LastError *string `json:"last_error,omitempty,omitzero"`

	// LastResultSummary corresponds to the JSON schema field "last_result_summary".
	LastResultSummary *string `json:"last_result_summary,omitempty,omitzero"`

	// LatestIteration corresponds to the JSON schema field "latest_iteration".
	LatestIteration *ReviewLoopIteration `json:"latest_iteration,omitempty,omitzero"`

	// LoopID corresponds to the JSON schema field "loop_id".
	LoopID string `json:"loop_id"`

	// PendingInteraction corresponds to the JSON schema field "pending_interaction".
	PendingInteraction *ReviewLoopInteraction `json:"pending_interaction,omitempty,omitzero"`

	// PendingInteractionID corresponds to the JSON schema field
	// "pending_interaction_id".
	PendingInteractionID *string `json:"pending_interaction_id,omitempty,omitzero"`

	// PresetID corresponds to the JSON schema field "preset_id".
	PresetID *string `json:"preset_id,omitempty,omitzero"`

	// RepoPath corresponds to the JSON schema field "repo_path".
	RepoPath string `json:"repo_path"`

	// ResolvedPrompt corresponds to the JSON schema field "resolved_prompt".
	ResolvedPrompt string `json:"resolved_prompt"`

	// SourceSessionID corresponds to the JSON schema field "source_session_id".
	SourceSessionID string `json:"source_session_id"`

	// Status corresponds to the JSON schema field "status".
	Status ReviewLoopRunStatus `json:"status"`

	// StopReason corresponds to the JSON schema field "stop_reason".
	StopReason *string `json:"stop_reason,omitempty,omitzero"`

	// UpdatedAt corresponds to the JSON schema field "updated_at".
	UpdatedAt string `json:"updated_at"`
}

type ReviewLoopRunStatus string

const ReviewLoopRunStatusAwaitingUser ReviewLoopRunStatus = "awaiting_user"
const ReviewLoopRunStatusCompleted ReviewLoopRunStatus = "completed"
const ReviewLoopRunStatusError ReviewLoopRunStatus = "error"
const ReviewLoopRunStatusRunning ReviewLoopRunStatus = "running"
const ReviewLoopRunStatusStopped ReviewLoopRunStatus = "stopped"

type ReviewLoopState struct {
	// AdvanceToken corresponds to the JSON schema field "advance_token".
	AdvanceToken string `json:"advance_token"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt string `json:"created_at"`

	// CustomPrompt corresponds to the JSON schema field "custom_prompt".
	CustomPrompt *string `json:"custom_prompt,omitempty,omitzero"`

	// IterationCount corresponds to the JSON schema field "iteration_count".
	IterationCount int `json:"iteration_count"`

	// IterationLimit corresponds to the JSON schema field "iteration_limit".
	IterationLimit int `json:"iteration_limit"`

	// LastAdvanceAt corresponds to the JSON schema field "last_advance_at".
	LastAdvanceAt *string `json:"last_advance_at,omitempty,omitzero"`

	// LastPromptAt corresponds to the JSON schema field "last_prompt_at".
	LastPromptAt *string `json:"last_prompt_at,omitempty,omitzero"`

	// LastUserInputAt corresponds to the JSON schema field "last_user_input_at".
	LastUserInputAt *string `json:"last_user_input_at,omitempty,omitzero"`

	// PresetID corresponds to the JSON schema field "preset_id".
	PresetID *string `json:"preset_id,omitempty,omitzero"`

	// ResolvedPrompt corresponds to the JSON schema field "resolved_prompt".
	ResolvedPrompt string `json:"resolved_prompt"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`

	// Status corresponds to the JSON schema field "status".
	Status ReviewLoopStatus `json:"status"`

	// StopReason corresponds to the JSON schema field "stop_reason".
	StopReason *string `json:"stop_reason,omitempty,omitzero"`

	// StopRequested corresponds to the JSON schema field "stop_requested".
	StopRequested bool `json:"stop_requested"`

	// UpdatedAt corresponds to the JSON schema field "updated_at".
	UpdatedAt string `json:"updated_at"`
}

type ReviewLoopStatus string

const ReviewLoopStatusAdvanceReceivedWaitingPrompt ReviewLoopStatus = "advance_received_waiting_prompt"
const ReviewLoopStatusCompleted ReviewLoopStatus = "completed"
const ReviewLoopStatusError ReviewLoopStatus = "error"
const ReviewLoopStatusRunning ReviewLoopStatus = "running"
const ReviewLoopStatusStopped ReviewLoopStatus = "stopped"
const ReviewLoopStatusWaitingForAgentAdvance ReviewLoopStatus = "waiting_for_agent_advance"

type ReviewLoopUpdatedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ReviewLoopRun corresponds to the JSON schema field "review_loop_run".
	ReviewLoopRun *ReviewLoopRun `json:"review_loop_run,omitempty,omitzero"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`
}

type ReviewState struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// RepoPath corresponds to the JSON schema field "repo_path".
	RepoPath string `json:"repo_path"`

	// ReviewID corresponds to the JSON schema field "review_id".
	ReviewID string `json:"review_id"`

	// ViewedFiles corresponds to the JSON schema field "viewed_files".
	ViewedFiles []string `json:"viewed_files"`
}

type Session struct {
	// Agent corresponds to the JSON schema field "agent".
	Agent SessionAgent `json:"agent"`

	// Branch corresponds to the JSON schema field "branch".
	Branch *string `json:"branch,omitempty,omitzero"`

	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`

	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID *string `json:"endpoint_id,omitempty,omitzero"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// IsWorktree corresponds to the JSON schema field "is_worktree".
	IsWorktree *bool `json:"is_worktree,omitempty,omitzero"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label"`

	// LastSeen corresponds to the JSON schema field "last_seen".
	LastSeen string `json:"last_seen"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo *string `json:"main_repo,omitempty,omitzero"`

	// Muted corresponds to the JSON schema field "muted".
	Muted bool `json:"muted"`

	// NeedsReviewAfterLongRun corresponds to the JSON schema field
	// "needs_review_after_long_run".
	NeedsReviewAfterLongRun *bool `json:"needs_review_after_long_run,omitempty,omitzero"`

	// Recoverable corresponds to the JSON schema field "recoverable".
	Recoverable *bool `json:"recoverable,omitempty,omitzero"`

	// State corresponds to the JSON schema field "state".
	State SessionState `json:"state"`

	// StateSince corresponds to the JSON schema field "state_since".
	StateSince string `json:"state_since"`

	// StateUpdatedAt corresponds to the JSON schema field "state_updated_at".
	StateUpdatedAt string `json:"state_updated_at"`

	// Todos corresponds to the JSON schema field "todos".
	Todos []string `json:"todos,omitempty,omitzero"`
}

type SessionAgent string

const SessionAgentClaude SessionAgent = "claude"
const SessionAgentCodex SessionAgent = "codex"
const SessionAgentCopilot SessionAgent = "copilot"
const SessionAgentPi SessionAgent = "pi"

type SessionExitedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ExitCode corresponds to the JSON schema field "exit_code".
	ExitCode int `json:"exit_code"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Signal corresponds to the JSON schema field "signal".
	Signal *string `json:"signal,omitempty,omitzero"`
}

type SessionRegisteredMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Session corresponds to the JSON schema field "session".
	Session Session `json:"session"`
}

type SessionState string

type SessionStateChangedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Session corresponds to the JSON schema field "session".
	Session Session `json:"session"`
}

const SessionStateIdle SessionState = "idle"
const SessionStateLaunching SessionState = "launching"
const SessionStatePendingApproval SessionState = "pending_approval"
const SessionStateUnknown SessionState = "unknown"
const SessionStateWaitingInput SessionState = "waiting_input"
const SessionStateWorking SessionState = "working"

type SessionTodosUpdatedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Session corresponds to the JSON schema field "session".
	Session Session `json:"session"`
}

type SessionUnregisteredMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Session corresponds to the JSON schema field "session".
	Session Session `json:"session"`
}

type SessionVisualizedMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type SessionsUpdatedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Sessions corresponds to the JSON schema field "sessions".
	Sessions []Session `json:"sessions,omitempty,omitzero"`
}

type SetEndpointRemoteWebMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled"`

	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID string `json:"endpoint_id"`
}

type SetReviewLoopIterationLimitMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// IterationLimit corresponds to the JSON schema field "iteration_limit".
	IterationLimit int `json:"iteration_limit"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`
}

type SetSessionResumeIDMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// ResumeSessionID corresponds to the JSON schema field "resume_session_id".
	ResumeSessionID string `json:"resume_session_id"`
}

type SetSettingMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Key corresponds to the JSON schema field "key".
	Key string `json:"key"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value"`
}

type SettingsUpdatedMessage struct {
	// ChangedKey corresponds to the JSON schema field "changed_key".
	ChangedKey *string `json:"changed_key,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Settings corresponds to the JSON schema field "settings".
	Settings RecordString `json:"settings,omitempty,omitzero"`

	// Success corresponds to the JSON schema field "success".
	Success *bool `json:"success,omitempty,omitzero"`
}

type SpawnResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type SpawnSessionMessage struct {
	// Agent corresponds to the JSON schema field "agent".
	Agent string `json:"agent"`

	// ClaudeExecutable corresponds to the JSON schema field "claude_executable".
	ClaudeExecutable *string `json:"claude_executable,omitempty,omitzero"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// CodexExecutable corresponds to the JSON schema field "codex_executable".
	CodexExecutable *string `json:"codex_executable,omitempty,omitzero"`

	// Cols corresponds to the JSON schema field "cols".
	Cols int `json:"cols"`

	// CopilotExecutable corresponds to the JSON schema field "copilot_executable".
	CopilotExecutable *string `json:"copilot_executable,omitempty,omitzero"`

	// Cwd corresponds to the JSON schema field "cwd".
	Cwd string `json:"cwd"`

	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID *string `json:"endpoint_id,omitempty,omitzero"`

	// Executable corresponds to the JSON schema field "executable".
	Executable *string `json:"executable,omitempty,omitzero"`

	// ForkSession corresponds to the JSON schema field "fork_session".
	ForkSession *bool `json:"fork_session,omitempty,omitzero"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label,omitempty,omitzero"`

	// PiExecutable corresponds to the JSON schema field "pi_executable".
	PiExecutable *string `json:"pi_executable,omitempty,omitzero"`

	// ResumePicker corresponds to the JSON schema field "resume_picker".
	ResumePicker *bool `json:"resume_picker,omitempty,omitzero"`

	// ResumeSessionID corresponds to the JSON schema field "resume_session_id".
	ResumeSessionID *string `json:"resume_session_id,omitempty,omitzero"`

	// Rows corresponds to the JSON schema field "rows".
	Rows int `json:"rows"`

	// YoloMode corresponds to the JSON schema field "yolo_mode".
	YoloMode *bool `json:"yolo_mode,omitempty,omitzero"`
}

type StartReviewLoopMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// HandoffPayloadJson corresponds to the JSON schema field "handoff_payload_json".
	HandoffPayloadJson *string `json:"handoff_payload_json,omitempty,omitzero"`

	// IterationLimit corresponds to the JSON schema field "iteration_limit".
	IterationLimit int `json:"iteration_limit"`

	// PresetID corresponds to the JSON schema field "preset_id".
	PresetID *string `json:"preset_id,omitempty,omitzero"`

	// Prompt corresponds to the JSON schema field "prompt".
	Prompt string `json:"prompt"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`
}

type StateMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// State corresponds to the JSON schema field "state".
	State string `json:"state"`
}

type StopMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// TranscriptPath corresponds to the JSON schema field "transcript_path".
	TranscriptPath string `json:"transcript_path"`
}

type StopReviewLoopMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`
}

type SubscribeGitStatusMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`
}

type TodosMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Todos corresponds to the JSON schema field "todos".
	Todos []string `json:"todos"`
}

type UnregisterMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type UnsubscribeGitStatusMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`
}

type UpdateCommentMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// CommentID corresponds to the JSON schema field "comment_id".
	CommentID string `json:"comment_id"`

	// Content corresponds to the JSON schema field "content".
	Content string `json:"content"`
}

type UpdateCommentResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type UpdateEndpointMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty,omitzero"`

	// EndpointID corresponds to the JSON schema field "endpoint_id".
	EndpointID string `json:"endpoint_id"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero"`

	// SshTarget corresponds to the JSON schema field "ssh_target".
	SshTarget *string `json:"ssh_target,omitempty,omitzero"`
}

type WebSocketEvent struct {
	// Action corresponds to the JSON schema field "action".
	Action *string `json:"action,omitempty,omitzero"`

	// Authors corresponds to the JSON schema field "authors".
	Authors []AuthorState `json:"authors,omitempty,omitzero"`

	// BaseRef corresponds to the JSON schema field "base_ref".
	BaseRef *string `json:"base_ref,omitempty,omitzero"`

	// Branch corresponds to the JSON schema field "branch".
	Branch *string `json:"branch,omitempty,omitzero"`

	// Branches corresponds to the JSON schema field "branches".
	Branches []Branch `json:"branches,omitempty,omitzero"`

	// Cloned corresponds to the JSON schema field "cloned".
	Cloned *bool `json:"cloned,omitempty,omitzero"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd *string `json:"cmd,omitempty,omitzero"`

	// Cols corresponds to the JSON schema field "cols".
	Cols *int `json:"cols,omitempty,omitzero"`

	// Conflict corresponds to the JSON schema field "conflict".
	Conflict *bool `json:"conflict,omitempty,omitzero"`

	// Data corresponds to the JSON schema field "data".
	Data *string `json:"data,omitempty,omitzero"`

	// Directory corresponds to the JSON schema field "directory".
	Directory *string `json:"directory,omitempty,omitzero"`

	// Dirty corresponds to the JSON schema field "dirty".
	Dirty *bool `json:"dirty,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ExitCode corresponds to the JSON schema field "exit_code".
	ExitCode *int `json:"exit_code,omitempty,omitzero"`

	// Files corresponds to the JSON schema field "files".
	Files []BranchDiffFile `json:"files,omitempty,omitzero"`

	// Found corresponds to the JSON schema field "found".
	Found *bool `json:"found,omitempty,omitzero"`

	// ID corresponds to the JSON schema field "id".
	ID *string `json:"id,omitempty,omitzero"`

	// LastSeq corresponds to the JSON schema field "last_seq".
	LastSeq *int `json:"last_seq,omitempty,omitzero"`

	// Modified corresponds to the JSON schema field "modified".
	Modified *string `json:"modified,omitempty,omitzero"`

	// Original corresponds to the JSON schema field "original".
	Original *string `json:"original,omitempty,omitzero"`

	// PaneID corresponds to the JSON schema field "pane_id".
	PaneID *string `json:"pane_id,omitempty,omitzero"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty,omitzero"`

	// Pid corresponds to the JSON schema field "pid".
	Pid *int `json:"pid,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion *string `json:"protocol_version,omitempty,omitzero"`

	// Prs corresponds to the JSON schema field "prs".
	Prs []PR `json:"prs,omitempty,omitzero"`

	// RateLimitResetAt corresponds to the JSON schema field "rate_limit_reset_at".
	RateLimitResetAt *string `json:"rate_limit_reset_at,omitempty,omitzero"`

	// RateLimitResource corresponds to the JSON schema field "rate_limit_resource".
	RateLimitResource *string `json:"rate_limit_resource,omitempty,omitzero"`

	// Reason corresponds to the JSON schema field "reason".
	Reason *string `json:"reason,omitempty,omitzero"`

	// RecentLocations corresponds to the JSON schema field "recent_locations".
	RecentLocations []RecentLocation `json:"recent_locations,omitempty,omitzero"`

	// Repos corresponds to the JSON schema field "repos".
	Repos []RepoState `json:"repos,omitempty,omitzero"`

	// ReviewLoopRun corresponds to the JSON schema field "review_loop_run".
	ReviewLoopRun *ReviewLoopRun `json:"review_loop_run,omitempty,omitzero"`

	// Rows corresponds to the JSON schema field "rows".
	Rows *int `json:"rows,omitempty,omitzero"`

	// Running corresponds to the JSON schema field "running".
	Running *bool `json:"running,omitempty,omitzero"`

	// RuntimeID corresponds to the JSON schema field "runtime_id".
	RuntimeID *string `json:"runtime_id,omitempty,omitzero"`

	// ScreenCols corresponds to the JSON schema field "screen_cols".
	ScreenCols *int `json:"screen_cols,omitempty,omitzero"`

	// ScreenCursorVisible corresponds to the JSON schema field
	// "screen_cursor_visible".
	ScreenCursorVisible *bool `json:"screen_cursor_visible,omitempty,omitzero"`

	// ScreenCursorX corresponds to the JSON schema field "screen_cursor_x".
	ScreenCursorX *int `json:"screen_cursor_x,omitempty,omitzero"`

	// ScreenCursorY corresponds to the JSON schema field "screen_cursor_y".
	ScreenCursorY *int `json:"screen_cursor_y,omitempty,omitzero"`

	// ScreenRows corresponds to the JSON schema field "screen_rows".
	ScreenRows *int `json:"screen_rows,omitempty,omitzero"`

	// ScreenSnapshot corresponds to the JSON schema field "screen_snapshot".
	ScreenSnapshot *string `json:"screen_snapshot,omitempty,omitzero"`

	// ScreenSnapshotFresh corresponds to the JSON schema field
	// "screen_snapshot_fresh".
	ScreenSnapshotFresh *bool `json:"screen_snapshot_fresh,omitempty,omitzero"`

	// Scrollback corresponds to the JSON schema field "scrollback".
	Scrollback *string `json:"scrollback,omitempty,omitzero"`

	// ScrollbackTruncated corresponds to the JSON schema field
	// "scrollback_truncated".
	ScrollbackTruncated *bool `json:"scrollback_truncated,omitempty,omitzero"`

	// Seq corresponds to the JSON schema field "seq".
	Seq *int `json:"seq,omitempty,omitzero"`

	// Session corresponds to the JSON schema field "session".
	Session *Session `json:"session,omitempty,omitzero"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID *string `json:"session_id,omitempty,omitzero"`

	// Sessions corresponds to the JSON schema field "sessions".
	Sessions []Session `json:"sessions,omitempty,omitzero"`

	// Settings corresponds to the JSON schema field "settings".
	Settings RecordString `json:"settings,omitempty,omitzero"`

	// Signal corresponds to the JSON schema field "signal".
	Signal *string `json:"signal,omitempty,omitzero"`

	// Staged corresponds to the JSON schema field "staged".
	Staged []GitFileChange `json:"staged,omitempty,omitzero"`

	// StashRef corresponds to the JSON schema field "stash_ref".
	StashRef *string `json:"stash_ref,omitempty,omitzero"`

	// Success corresponds to the JSON schema field "success".
	Success *bool `json:"success,omitempty,omitzero"`

	// TargetPath corresponds to the JSON schema field "target_path".
	TargetPath *string `json:"target_path,omitempty,omitzero"`

	// Unstaged corresponds to the JSON schema field "unstaged".
	Unstaged []GitFileChange `json:"unstaged,omitempty,omitzero"`

	// Untracked corresponds to the JSON schema field "untracked".
	Untracked []GitFileChange `json:"untracked,omitempty,omitzero"`

	// Warnings corresponds to the JSON schema field "warnings".
	Warnings []DaemonWarning `json:"warnings,omitempty,omitzero"`

	// Workspace corresponds to the JSON schema field "workspace".
	Workspace *WorkspaceSnapshot `json:"workspace,omitempty,omitzero"`

	// Workspaces corresponds to the JSON schema field "workspaces".
	Workspaces []WorkspaceSnapshot `json:"workspaces,omitempty,omitzero"`

	// Worktrees corresponds to the JSON schema field "worktrees".
	Worktrees []Worktree `json:"worktrees,omitempty,omitzero"`
}

type WontFixCommentMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// CommentID corresponds to the JSON schema field "comment_id".
	CommentID string `json:"comment_id"`

	// WontFix corresponds to the JSON schema field "wont_fix".
	WontFix bool `json:"wont_fix"`
}

type WontFixCommentResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type WorkspaceActionResultMessage struct {
	// Action corresponds to the JSON schema field "action".
	Action string `json:"action"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// PaneID corresponds to the JSON schema field "pane_id".
	PaneID *string `json:"pane_id,omitempty,omitzero"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type WorkspaceClosePaneMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// PaneID corresponds to the JSON schema field "pane_id".
	PaneID string `json:"pane_id"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`
}

type WorkspaceFocusPaneMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// PaneID corresponds to the JSON schema field "pane_id".
	PaneID string `json:"pane_id"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`
}

type WorkspaceGetMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`
}

type WorkspacePane struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind WorkspacePaneKind `json:"kind"`

	// PaneID corresponds to the JSON schema field "pane_id".
	PaneID string `json:"pane_id"`

	// RuntimeID corresponds to the JSON schema field "runtime_id".
	RuntimeID *string `json:"runtime_id,omitempty,omitzero"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title"`
}

type WorkspacePaneKind string

const WorkspacePaneKindMain WorkspacePaneKind = "main"
const WorkspacePaneKindShell WorkspacePaneKind = "shell"

type WorkspaceRenamePaneMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// PaneID corresponds to the JSON schema field "pane_id".
	PaneID string `json:"pane_id"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title"`
}

type WorkspaceRuntimeExitedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ExitCode corresponds to the JSON schema field "exit_code".
	ExitCode int `json:"exit_code"`

	// PaneID corresponds to the JSON schema field "pane_id".
	PaneID string `json:"pane_id"`

	// RuntimeID corresponds to the JSON schema field "runtime_id".
	RuntimeID string `json:"runtime_id"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`

	// Signal corresponds to the JSON schema field "signal".
	Signal *string `json:"signal,omitempty,omitzero"`
}

type WorkspaceSnapshot struct {
	// ActivePaneID corresponds to the JSON schema field "active_pane_id".
	ActivePaneID string `json:"active_pane_id"`

	// LayoutJson corresponds to the JSON schema field "layout_json".
	LayoutJson string `json:"layout_json"`

	// Panes corresponds to the JSON schema field "panes".
	Panes []WorkspacePane `json:"panes"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`

	// UpdatedAt corresponds to the JSON schema field "updated_at".
	UpdatedAt *string `json:"updated_at,omitempty,omitzero"`
}

type WorkspaceSnapshotMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Workspace corresponds to the JSON schema field "workspace".
	Workspace WorkspaceSnapshot `json:"workspace"`
}

type WorkspaceSplitDirection string

const WorkspaceSplitDirectionHorizontal WorkspaceSplitDirection = "horizontal"
const WorkspaceSplitDirectionVertical WorkspaceSplitDirection = "vertical"

type WorkspaceSplitPaneMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Direction corresponds to the JSON schema field "direction".
	Direction WorkspaceSplitDirection `json:"direction"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`

	// TargetPaneID corresponds to the JSON schema field "target_pane_id".
	TargetPaneID string `json:"target_pane_id"`
}

type WorkspaceUpdatedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Workspace corresponds to the JSON schema field "workspace".
	Workspace WorkspaceSnapshot `json:"workspace"`
}

type Worktree struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt *string `json:"created_at,omitempty,omitzero"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}

type WorktreeCreatedEvent struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Worktrees corresponds to the JSON schema field "worktrees".
	Worktrees []Worktree `json:"worktrees"`
}

type WorktreeDeletedEvent struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Worktrees corresponds to the JSON schema field "worktrees".
	Worktrees []Worktree `json:"worktrees"`
}

type WorktreesUpdatedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Worktrees corresponds to the JSON schema field "worktrees".
	Worktrees []Worktree `json:"worktrees,omitempty,omitzero"`
}
