// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package protocol

type ApprovePRMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Number corresponds to the JSON schema field "number".
	Number int `json:"number"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type Branch struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`
}

type BranchesResultMessage struct {
	// Branches corresponds to the JSON schema field "branches".
	Branches []Branch `json:"branches"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type ClearSessionsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`
}

type CollapseRepoMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Collapsed corresponds to the JSON schema field "collapsed".
	Collapsed bool `json:"collapsed"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type CreateWorktreeFromBranchMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty"`
}

type CreateWorktreeMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty"`
}

type CreateWorktreeResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type DeleteBranchMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Force corresponds to the JSON schema field "force".
	Force bool `json:"force"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`
}

type DeleteBranchResultMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type DeleteWorktreeMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}

type DeleteWorktreeResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type FetchPRDetailsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type GetRecentLocationsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Limit corresponds to the JSON schema field "limit".
	Limit *int `json:"limit,omitempty"`
}

type GetSettingsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`
}

type HeartbeatMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type HeatState string

const HeatStateCold HeatState = "cold"
const HeatStateHot HeatState = "hot"
const HeatStateWarm HeatState = "warm"

type InjectTestPRMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// PR corresponds to the JSON schema field "pr".
	PR PR `json:"pr"`
}

type InjectTestSessionMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Session corresponds to the JSON schema field "session".
	Session Session `json:"session"`
}

type ListBranchesMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`
}

type ListWorktreesMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`
}

type MergePRMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Method corresponds to the JSON schema field "method".
	Method string `json:"method"`

	// Number corresponds to the JSON schema field "number".
	Number int `json:"number"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type MuteMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type MutePRMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type MuteRepoMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type PR struct {
	// ApprovedByMe corresponds to the JSON schema field "approved_by_me".
	ApprovedByMe bool `json:"approved_by_me"`

	// CIStatus corresponds to the JSON schema field "ci_status".
	CIStatus *string `json:"ci_status,omitempty"`

	// CommentCount corresponds to the JSON schema field "comment_count".
	CommentCount *int `json:"comment_count,omitempty"`

	// DetailsFetched corresponds to the JSON schema field "details_fetched".
	DetailsFetched bool `json:"details_fetched"`

	// DetailsFetchedAt corresponds to the JSON schema field "details_fetched_at".
	DetailsFetchedAt *string `json:"details_fetched_at,omitempty"`

	// HasNewChanges corresponds to the JSON schema field "has_new_changes".
	HasNewChanges bool `json:"has_new_changes"`

	// HeadBranch corresponds to the JSON schema field "head_branch".
	HeadBranch *string `json:"head_branch,omitempty"`

	// HeadSHA corresponds to the JSON schema field "head_sha".
	HeadSHA *string `json:"head_sha,omitempty"`

	// HeatState corresponds to the JSON schema field "heat_state".
	HeatState *HeatState `json:"heat_state,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// LastHeatActivityAt corresponds to the JSON schema field
	// "last_heat_activity_at".
	LastHeatActivityAt *string `json:"last_heat_activity_at,omitempty"`

	// LastPolled corresponds to the JSON schema field "last_polled".
	LastPolled string `json:"last_polled"`

	// LastUpdated corresponds to the JSON schema field "last_updated".
	LastUpdated string `json:"last_updated"`

	// Mergeable corresponds to the JSON schema field "mergeable".
	Mergeable *bool `json:"mergeable,omitempty"`

	// MergeableState corresponds to the JSON schema field "mergeable_state".
	MergeableState *string `json:"mergeable_state,omitempty"`

	// Muted corresponds to the JSON schema field "muted".
	Muted bool `json:"muted"`

	// Number corresponds to the JSON schema field "number".
	Number int `json:"number"`

	// Reason corresponds to the JSON schema field "reason".
	Reason string `json:"reason"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`

	// ReviewStatus corresponds to the JSON schema field "review_status".
	ReviewStatus *string `json:"review_status,omitempty"`

	// Role corresponds to the JSON schema field "role".
	Role PRRole `json:"role"`

	// State corresponds to the JSON schema field "state".
	State string `json:"state"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title"`

	// URL corresponds to the JSON schema field "url".
	URL string `json:"url"`
}

type PRActionResultMessage struct {
	// Action corresponds to the JSON schema field "action".
	Action string `json:"action"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Number corresponds to the JSON schema field "number".
	Number int `json:"number"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type PRRole string

const PRRoleAuthor PRRole = "author"
const PRRoleReviewer PRRole = "reviewer"

type PRVisitedMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type QueryMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Filter corresponds to the JSON schema field "filter".
	Filter *string `json:"filter,omitempty"`
}

type QueryPRsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Filter corresponds to the JSON schema field "filter".
	Filter *string `json:"filter,omitempty"`
}

type QueryReposMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Filter corresponds to the JSON schema field "filter".
	Filter *string `json:"filter,omitempty"`
}

type RateLimitedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ResetAt corresponds to the JSON schema field "reset_at".
	ResetAt string `json:"reset_at"`

	// Resource corresponds to the JSON schema field "resource".
	Resource string `json:"resource"`
}

type RecentLocation struct {
	// Label corresponds to the JSON schema field "label".
	Label string `json:"label"`

	// LastSeen corresponds to the JSON schema field "last_seen".
	LastSeen string `json:"last_seen"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// UseCount corresponds to the JSON schema field "use_count".
	UseCount int `json:"use_count"`
}

type RecentLocationsResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Locations corresponds to the JSON schema field "locations".
	Locations []RecentLocation `json:"locations"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type RefreshPRsMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`
}

type RefreshPRsResultMessage struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type RegisterMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Dir corresponds to the JSON schema field "dir".
	Dir string `json:"dir"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label,omitempty"`
}

type RepoState struct {
	// Collapsed corresponds to the JSON schema field "collapsed".
	Collapsed bool `json:"collapsed"`

	// Muted corresponds to the JSON schema field "muted".
	Muted bool `json:"muted"`

	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo"`
}

type Response struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Ok corresponds to the JSON schema field "ok".
	Ok bool `json:"ok"`

	// Prs corresponds to the JSON schema field "prs".
	Prs []PR `json:"prs,omitempty"`

	// Repos corresponds to the JSON schema field "repos".
	Repos []RepoState `json:"repos,omitempty"`

	// Sessions corresponds to the JSON schema field "sessions".
	Sessions []Session `json:"sessions,omitempty"`
}

type Session struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch *string `json:"branch,omitempty"`

	// Directory corresponds to the JSON schema field "directory".
	Directory string `json:"directory"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// IsWorktree corresponds to the JSON schema field "is_worktree".
	IsWorktree *bool `json:"is_worktree,omitempty"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label"`

	// LastSeen corresponds to the JSON schema field "last_seen".
	LastSeen string `json:"last_seen"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo *string `json:"main_repo,omitempty"`

	// Muted corresponds to the JSON schema field "muted".
	Muted bool `json:"muted"`

	// State corresponds to the JSON schema field "state".
	State SessionState `json:"state"`

	// StateSince corresponds to the JSON schema field "state_since".
	StateSince string `json:"state_since"`

	// StateUpdatedAt corresponds to the JSON schema field "state_updated_at".
	StateUpdatedAt string `json:"state_updated_at"`

	// Todos corresponds to the JSON schema field "todos".
	Todos []string `json:"todos,omitempty"`
}

type SessionState string

const SessionStateIdle SessionState = "idle"
const SessionStateWaitingInput SessionState = "waiting_input"
const SessionStateWorking SessionState = "working"

type SetSettingMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// Key corresponds to the JSON schema field "key".
	Key string `json:"key"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value"`
}

type StateMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// State corresponds to the JSON schema field "state".
	State string `json:"state"`
}

type StopMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// TranscriptPath corresponds to the JSON schema field "transcript_path".
	TranscriptPath string `json:"transcript_path"`
}

type SwitchBranchMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`
}

type SwitchBranchResultMessage struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type TodosMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Todos corresponds to the JSON schema field "todos".
	Todos []string `json:"todos"`
}

type UnregisterMessage struct {
	// Cmd corresponds to the JSON schema field "cmd".
	Cmd string `json:"cmd"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`
}

type WebSocketEvent struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch *string `json:"branch,omitempty"`

	// Branches corresponds to the JSON schema field "branches".
	Branches []Branch `json:"branches,omitempty"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion *string `json:"protocol_version,omitempty"`

	// Prs corresponds to the JSON schema field "prs".
	Prs []PR `json:"prs,omitempty"`

	// RateLimitResetAt corresponds to the JSON schema field "rate_limit_reset_at".
	RateLimitResetAt *string `json:"rate_limit_reset_at,omitempty"`

	// RateLimitResource corresponds to the JSON schema field "rate_limit_resource".
	RateLimitResource *string `json:"rate_limit_resource,omitempty"`

	// RecentLocations corresponds to the JSON schema field "recent_locations".
	RecentLocations []RecentLocation `json:"recent_locations,omitempty"`

	// Repos corresponds to the JSON schema field "repos".
	Repos []RepoState `json:"repos,omitempty"`

	// Session corresponds to the JSON schema field "session".
	Session *Session `json:"session,omitempty"`

	// Sessions corresponds to the JSON schema field "sessions".
	Sessions []Session `json:"sessions,omitempty"`

	// Settings corresponds to the JSON schema field "settings".
	Settings map[string]interface{} `json:"settings,omitempty"`

	// Success corresponds to the JSON schema field "success".
	Success *bool `json:"success,omitempty"`

	// Worktrees corresponds to the JSON schema field "worktrees".
	Worktrees []Worktree `json:"worktrees,omitempty"`
}

type Worktree struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt *string `json:"created_at,omitempty"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}

type WorktreeCreatedEvent struct {
	// Branch corresponds to the JSON schema field "branch".
	Branch string `json:"branch"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// MainRepo corresponds to the JSON schema field "main_repo".
	MainRepo string `json:"main_repo"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}
