#!/bin/bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
app_dir="$(cd "$script_dir/.." && pwd)"
repo_dir="$(cd "$app_dir/.." && pwd)"

pin_file="$repo_dir/ghostty-vt.pin"
builder="$script_dir/build-ghostty-vt-wasm.sh"
compat_patch="$app_dir/vendor/ghostty-vt/ghostty-web-v0.4.0-compat.patch"
compat_source="$app_dir/vendor/ghostty-vt/ghostty-web-v0.4.0-compat.zig"
wasm="$app_dir/vendor/ghostty-vt/ghostty-vt.wasm"
lock_file="$app_dir/vendor/ghostty-vt/ghostty-vt.lock"

sha256_file() {
  local path="$1"
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$path" | awk '{print $1}'
  elif command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$path" | awk '{print $1}'
  elif command -v openssl >/dev/null 2>&1; then
    openssl dgst -sha256 "$path" | awk '{print $NF}'
  else
    echo "error: no SHA-256 implementation found (tried shasum, sha256sum, openssl)" >&2
    return 1
  fi
}

pin_value() {
  grep -vE '^\s*(#|$)' "$pin_file" | head -n1 | tr -d '[:space:]'
}

lock_value() {
  local key="$1"
  awk -F= -v key="$key" '$1 == key {sub(/^[^=]*=/, ""); print; exit}' "$lock_file"
}

fail_stale() {
  local field="$1"
  local want="$2"
  local got="$3"
  echo "error: vendored Ghostty WASM lock is stale: $field" >&2
  echo "       locked: $want" >&2
  echo "       actual: $got" >&2
  echo "       rebuild with app/scripts/build-ghostty-vt-wasm.sh" >&2
  exit 1
}

write_lock() {
  local zig_version="$1"
  case "$zig_version" in
    0.16.*) ;;
    *) echo "error: lock requires a Zig 0.16.x build, got $zig_version" >&2; exit 1 ;;
  esac

  local tmp
  tmp="$(mktemp "${lock_file}.XXXXXX")"
  trap 'rm -f "$tmp"' EXIT
  {
    echo "# Vendored Ghostty WASM provenance. Generated by build-ghostty-vt-wasm.sh."
    echo "# Normal app builds and tests verify every input and the output hash."
    echo "pin=$(pin_value)"
    echo "zig_version=$zig_version"
    echo "builder_sha256=$(sha256_file "$builder")"
    echo "compat_patch_sha256=$(sha256_file "$compat_patch")"
    echo "compat_source_sha256=$(sha256_file "$compat_source")"
    echo "wasm_sha256=$(sha256_file "$wasm")"
  } >"$tmp"
  mv "$tmp" "$lock_file"
  trap - EXIT
}

verify_lock() {
  if [[ ! -f "$lock_file" ]]; then
    echo "error: missing $lock_file; rebuild with app/scripts/build-ghostty-vt-wasm.sh" >&2
    exit 1
  fi

  local field want got
  while IFS='|' read -r field want got; do
    if [[ -z "$want" ]]; then
      echo "error: missing $field in $lock_file" >&2
      exit 1
    fi
    [[ "$want" == "$got" ]] || fail_stale "$field" "$want" "$got"
  done <<EOF
pin|$(lock_value pin)|$(pin_value)
builder_sha256|$(lock_value builder_sha256)|$(sha256_file "$builder")
compat_patch_sha256|$(lock_value compat_patch_sha256)|$(sha256_file "$compat_patch")
compat_source_sha256|$(lock_value compat_source_sha256)|$(sha256_file "$compat_source")
wasm_sha256|$(lock_value wasm_sha256)|$(sha256_file "$wasm")
EOF

  local zig_version
  zig_version="$(lock_value zig_version)"
  case "$zig_version" in
    0.16.*) ;;
    *) echo "error: invalid zig_version in $lock_file: ${zig_version:-missing}" >&2; exit 1 ;;
  esac

  echo "Ghostty WASM provenance verified (pin $(pin_value), Zig $zig_version)"
}

case "${1:-verify}" in
  write)
    [[ $# -eq 2 ]] || { echo "usage: $0 write <zig-version>" >&2; exit 2; }
    write_lock "$2"
    ;;
  verify)
    [[ $# -eq 1 || $# -eq 0 ]] || { echo "usage: $0 [verify]" >&2; exit 2; }
    verify_lock
    ;;
  *)
    echo "usage: $0 [verify] | write <zig-version>" >&2
    exit 2
    ;;
esac
